Create redux-and-saga
uktrade/data-hub-frontend pull request #2886
Opened 2020-08-07 15:06 UTC by debitan

High level documentation of how to add a new saga task and accompanying redux actions/reducers

## Description of change

_Document what the PR does and why the change is needed_

## Test instructions

_What should I see?_

## Screenshots
### Before

_Add a screenshot_

### After

_Add a screenshot_

## Checklist

[//]: # "When submitting a PR make sure the code review guidelines have been satisfied.
https://github.com/uktrade/data-hub-frontend/blob/master/docs/Code%20review%20guidelines.md"

- [ ] Has the branch been rebased to master?
- [ ] Automated tests (Any of the following when applicable: Unit, Functional or Acceptance)
- [ ] Manual compatibility testing (Browsers: Chrome, Firefox, IE11, Safari)

2020-08-12 09:01 UTC, peterhudec commented on docs/redux-and-saga.md
> +export const TASK_GET_PIPELINE_LIST = "TASK_GET_PIPELINE_LIST"
I don't think it's necessary to keep the _task names_ in constants and makes the code less readable. The `Task` component will throw a _task not registered_ error in case of a typo.

2020-08-12 09:12 UTC, peterhudec commented on docs/redux-and-saga.md
> +Now it's time to hook up your task to your React component. You can do this in two ways with our `Task` wrapper - either with `Task.Status` or `getTask`. `Task.Status` gives you a built in loading bo
I would add a referrences to docstrings of all the task related components which explain all their options, e.g. the `Task.Status` takes the `renderStatus` and `renderError` which you can use to override its default progress and error views.

* [`Task` docs](https://github.com/uktrade/data-hub-frontend/blob/master/src/client/components/Task/index.jsx#L47-L100)
* [`Task.Status` docs](https://github.com/uktrade/data-hub-frontend/blob/master/src/client/components/Task/index.jsx#L164-L189)
* [`Task.StartOnRender` docs](https://github.com/uktrade/data-hub-frontend/blob/master/src/client/components/Task/index.jsx#L129-L140)

2020-08-12 09:16 UTC, peterhudec commented on docs/redux-and-saga.md
> +This is the last step. We just need to hook up our reducer to the Redux store.
It would be more precise to say that "we need to compose our reducer into the root reducer".

2020-08-12 10:16 UTC, debitan commented on docs/redux-and-saga.md
> +export const TASK_GET_PIPELINE_LIST = "TASK_GET_PIPELINE_LIST"
Ok. Will take it out. Just a pattern I've seen emerging from existing examples.

2020-08-12 10:17 UTC, debitan commented on docs/redux-and-saga.md
> +Now it's time to hook up your task to your React component. You can do this in two ways with our `Task` wrapper - either with `Task.Status` or `getTask`. `Task.Status` gives you a built in loading bo
I'll reference the doc strings. Was intending to keep this high level/an overview - but if people want to dive deeper they can in your doc strings.

2020-08-12 10:18 UTC, debitan commented on docs/redux-and-saga.md
> +This is the last step. We just need to hook up our reducer to the Redux store.
Will change.

2020-08-12 10:18 UTC, debitan commented on docs/redux-and-saga.md
> +This is where you will put your task. This is a standard JavaScript function that will make an axios call through the api-proxy (so be sure to add your api url to the api-proxy allowlist)
Will add.

2020-08-12 10:28 UTC, debitan commented on docs/redux-and-saga.md
> +export const TASK_GET_PIPELINE_LIST = "TASK_GET_PIPELINE_LIST"
On second thoughts I will leave it in but make the point that it isn't necessary

2020-08-28 10:54 UTC, peterhudec requested changes
Almost there, but there are still some typos.

2020-08-28 10:54 UTC, peterhudec commented on docs/Redux and Saga.md
> +```
Let Markdown know that it's TypeScript for better syntax highlighting by adding `ts` after the opening backticks: ```` ```ts ````

2020-08-28 10:54 UTC, peterhudec commented on docs/Redux and Saga.md
> +Wrapping our saga tasks we have a custom `Task` component and some other custom implementations with Redux. This can mean that just reading the Redux and Saga docs might not be enough to smoothly get
I would wrap the `` `Task` `` in a link to its source: ``[`Task`](https://github.com/uktrade/data-hub-frontend/blob/master/src/client/components/Task/index.jsx#L47-L101)``.

2020-08-28 10:54 UTC, peterhudec commented on docs/Redux and Saga.md
> +            [TASK_GET_PIPELINE_LIST]: pipelineTasks.getPIpelineList,
Typo in `getP(I)pelineList`

2020-08-28 10:54 UTC, peterhudec commented on docs/Redux and Saga.md
> +export const PIPELINE**LIST_LOADED = "PIPELINE__LIST_LOADED"
It probably should be `export const PIPELINE__LIST_LOADED = "PIPELINE__LIST_LOADED"`

2020-08-28 15:24 UTC, mcbhenwood commented
While I think it can be enormously helpful having documentation to assist developers, publishing docs of this detail really does place a heavy burden on future developers to repeatedly parse these docs and make sure their own changes do not render the docs inaccurate or obsolete. Perhaps you need a comment in the actual JS code modules with 'links' to the location of these docs saying "if you materially alter this then please update the docs".

Of course, one could argue that the _need_ for such docs suggests an implementation which is in some way inscrutable or too "tightly wound" to be understood easily by simply reading. While conciseness and purity are excellent values to strive for, I feel that in the future when we are adding what is essentially our own framework tooling to a repo, it should be done as a joint effort including within that effort team members of lesser experience, so that we can build out solutions which can be understood simply by all, without the need for paragraphs of explanation.

2020-09-07 11:52 UTC, peterhudec approved these changes

2020-09-07 11:54 UTC, ian-leggett approved these changes

2020-09-07 14:10 UTC, merged