feature: reactify investment projects collection list
uktrade/data-hub-frontend pull request #2905
Opened 2020-08-14 15:02 UTC by debitan

## Description of change

_Document what the PR does and why the change is needed_

## Test instructions

_What should I see?_

## Screenshots
### Before

_Add a screenshot_

### After

_Add a screenshot_

## Checklist

[//]: # "When submitting a PR make sure the code review guidelines have been satisfied.
https://github.com/uktrade/data-hub-frontend/blob/master/docs/Code%20review%20guidelines.md"

- [ ] Has the branch been rebased to master?
- [ ] Automated tests (Any of the following when applicable: Unit, Functional or Acceptance)
- [ ] Manual compatibility testing (Browsers: Chrome, Firefox, IE11, Safari)

2020-09-21 14:25 UTC, peterhudec requested changes
Looks promissing, but there are a couple of things that could be improved.

2020-09-22 09:46 UTC, debitan reviewed
I can't request changes as I'm actually the original author of the PR haha. But there are some changes I would like to see. The main ones I would call out are:

1. Remove the `CollectionDownload` section. It doesn't work as it is anyway and we can look at it in isolation is a separate PR that branches of this feature branch. This PR is huge as it is, so we should take the opportunity to trim it down where we can. 

2. Avoid spreading props into components. It makes the code much easier to understand when we clearly name our props. Some of this will be taken care of by the `state2props` suggested by @peterhudec anyway. 

3. The pagination UI doesn't work correctly. We need to reinstate the `activePage` prop. 

4. We still are storing some state in the redux store though our dispatch actions and we don't need to anymore. For this feature we are all in storing the state in the URL / react router search. Following this through will allow us to remove a good number of lines of code.

2020-09-22 09:46 UTC, debitan commented on src/client/components/CollectionList/index.jsx
> +                    filters={filters}
You accidentally deleted `activePage`. This means that when you change page the UI for the pagination doesn't update.

2020-09-22 09:46 UTC, debitan commented on src/apps/investments/client/projects/reducer.js
> +        isComplete: true,
Not sure that will work because the default value for results is an empty array. However a legitimate returned value from the API call is that results is still an empty array. Therefore there is no change and no way to know if the task is complete. The reason we need the `isComplete` is because that is the only way to know if the task has finished or not. If we don't have it we get a flash or the component with no results, then the loading spinner, and then the component with results. `isComplete` allows us to not show the flash of the empty component and we only show it once the task has finished loading the data. 

This is the problem that my now closed PR about adding a finished flag to the tasks was trying to achieve at a task level rather than having to do it for individual components. However, I couldn't get it to work. We could really do with your help on that problem.

2020-09-22 09:46 UTC, debitan commented on src/apps/investments/client/projects/reducer.js
> +        isComplete: true,
For now though, I would say `isComplete` is absolutely necessary for a better UX.

2020-09-22 09:46 UTC, debitan commented on src/apps/investments/client/projects/tasks.js
> +  })
Ideally we would not have to write this handleError function each time we get a result back from a task. We should centralise this and import it. I can't see that each of these implementations does anything different. 

I'm not suggesting this is centralised as part of this PR. But should be tackled soon to enable reliable and consistent error handling.

2020-09-22 09:46 UTC, debitan commented on src/apps/investments/client/projects/tasks.js
> +      ...parsedQuery,
I think this comes back to spreading props vs calling them out by name. 

However, the real issue here I think is that we no longer need to pass in `page` and `filters` as all of this information is now contained within `search`. There are some parts of the code that are still in the old mindset of getting state from redux, but here we are exclusively dealing with state contained in the URL / react router search. But yeah, we may want to deconstruct search before it gets here - but I'm not really fussed about that.

2020-09-22 09:46 UTC, debitan commented on src/apps/investments/client/projects/tasks.js
> +      )
This is because of the way react router handles parsing the URL. If there is only one of a thing it is a string rather than a single thing in an array. If there are multiple it is an array. So we've got to handle the changing type of data somehow. If it isn't in a conditional here then we would just have to massage it before hand - so I can't really see a benefit to doing that.

2020-09-22 09:46 UTC, debitan commented on src/apps/investments/controllers/projects.js
> -    )
We've not actually replaced this in the code yet. The download doesn't work. I agree that we should delete this server side code and replace it with a client based solution, but as we don't have that yet it might be best to remove the whole download section from this PR:

1. to make this PR smaller and more focused
2. to allow us to view the download related code in isolation - making the second PR small and focused.

2020-09-22 09:46 UTC, debitan commented on src/apps/investments/transformers/collection.js
> +        estimated_land_date && moment(estimated_land_date).format('MMMM YYYY'),
we probably want to try to start using `date-fns`. However, there should be a ready built function for this in `date-utils`. So I would advise using that function from `date-utils` and then we can swap out `moment` for `date-fns` in the `utils` and do it all in one go later. 

If `date-utils` doesn't yet cover this formatting eventuality, then we should add it there.

2020-09-22 09:46 UTC, debitan commented on src/apps/investments/transformers/collection.js
> +    subheading: `Project code ${project_code}`,
Agreed. We should start doing as much transformation in the view layer as possible for architectural cleanliness.

2020-09-22 09:46 UTC, debitan commented on src/client/actions.js
> +}
I initially saw this and thought this is brilliant as the file is hell to look at. But you make a good point. This was the whole point of this file - to namespace the actions. However, a point outside of the scope of this PR, this file is becoming so unwieldy. Maybe we should think of an alternative to this solution. But, it is doing its job for now.

2020-09-22 09:46 UTC, debitan commented on src/client/components/CollectionList/CollectionDownload.jsx
> +// TODO: we need to lift this out to the button component, as we don't have a link styled as a button
let's create a ticket for this in our backlog and then we can hopefully bin this `TODO` asap.

2020-09-22 09:46 UTC, debitan commented on src/client/components/CollectionList/CollectionDownload.jsx
> +      href={`${downloadUrl}s/export${decodeURIComponent(search)}`.toLowerCase()}
This doesn't appear to work anyway. I suggested in a comment buried above that we should probably remove the whole download functionality from this PR and tackle it separately.

2020-09-22 09:46 UTC, debitan commented on src/client/components/CollectionList/CollectionDownloadMessage.jsx
> +    )
Why are they redundant?

2020-09-22 09:46 UTC, debitan commented on src/client/components/CollectionList/CollectionDownloadMessage.jsx
> +    )
But either way. Let's separate this into a new PR.

2020-09-22 09:46 UTC, debitan commented on src/client/components/CollectionList/index.jsx
> +  task,
I don't agree and would mark this clearly as an optional comment.

2020-09-22 09:46 UTC, debitan commented on src/client/components/CollectionList/index.jsx
> +            startOnRender={task.startOnRender}
I'd prefer to see it as is - named props rather than a spread.

2020-09-22 09:46 UTC, debitan commented on src/client/components/Filters/elements/FilterAdvisersTypeAhead/index.jsx
> +      >
I think I see what you mean here. This `Task.Status` should clearly be the one to look up the adviser names. It is never going to be anything else so let's just have it here rather than pass it in as a prop.

2020-09-22 09:46 UTC, debitan commented on src/client/components/Filters/elements/FilterSelectDropdown/index.jsx
> +}
Out of interest do you prefer default props to be defined in the function. e.g. `({initialValue = '', options=[] ...}) =>`

If so, I would definitely agree.

2020-09-22 09:46 UTC, debitan commented on src/client/utils/formatAdviser.js
> +const parseAdviserData = (advisers) => {
Makes sense. Unless you foresee other filters needing it? 

Even then, only if it is definitely a filter that we will add now on this page in the next few weeks would I separate it out ahead of time.

2020-09-24 12:23 UTC, paulgain requested changes

2020-09-24 12:27 UTC, paulgain commented
**IMPORTANT**
This is a large piece of functionality, it's not hidden behind an express route or an environment variable, if anything goes wrong in production we don’t have the ability to swap it out.

2020-09-24 13:24 UTC, rachaelcodes commented on src/apps/investments/controllers/projects.js
> -    )
Can we hide the button/link in the meantime before the fix?

2020-09-25 12:21 UTC, mcbhenwood commented on src/apps/investments/client/profiles/LargeCapitalProfileCollection.jsx
> +  const { page } = props[ID]
As discussed @ian-leggett, agreed it's better to knit the various state elements together in `stateToProps` and pass an object that's a contract between the `stateToProps` func and the component.

2020-09-25 12:22 UTC, mcbhenwood commented on src/client/components/CollectionList/index.jsx
> +            startOnRender={task.startOnRender}
As discussed @ian-leggett using a spread means we aren't needlessly unpacking values just to repack them for unpacking later in `<Task.Status>`

2020-09-25 12:23 UTC, mcbhenwood commented on src/apps/investments/client/profiles/LargeCapitalProfileCollection.jsx
> +  }
As discussed @ian-leggett we're moving to a flat pair of constants here which are named to reflect the fact that they are props for a task so `collectionListTaskProps` etc.

2020-09-25 12:24 UTC, mcbhenwood commented on src/client/actions.js
> +}
Also agreed although I think 'ugly' is a bit strong :)

2020-09-25 12:26 UTC, mcbhenwood commented on src/client/components/CollectionList/index.jsx
> +  task,
Agrreeing with @peterhudec  - See later comment regarding ditching this structure and using flat, `xxxProps` constant names instead: https://github.com/uktrade/data-hub-frontend/pull/2905#discussion_r494950783

2020-09-26 08:50 UTC, ian-leggett commented on src/client/actions.js
> +}
Agree 👍

2020-09-26 08:59 UTC, ian-leggett commented on src/apps/investments/client/profiles/LargeCapitalProfileCollection.jsx
> +  const { page } = props[ID]
Agree I really overlooked this thanks 👍

2020-09-26 09:00 UTC, ian-leggett commented on src/client/components/CollectionList/index.jsx
> +            startOnRender={task.startOnRender}
I now just forward these props on thanks 👍

2020-09-26 09:00 UTC, ian-leggett commented on src/client/components/CollectionList/index.jsx
> +  task,
Agree 👍

2020-09-26 09:00 UTC, ian-leggett commented on src/apps/investments/client/profiles/LargeCapitalProfileCollection.jsx
> +  }
Flattened these out into consts 👍

2020-10-12 14:45 UTC, ian-leggett commented on src/client/components/Filters/elements/FilterAdvisersTypeAhead/index.jsx
> +      >
We could potentially run more than one adviser typeahead filter so this is why I have not baked the values inside this file. Also like Dave mentioned we will always use the task component here so I didn't see any reason to lift it out.

2020-10-12 14:51 UTC, ian-leggett commented on src/client/components/Filters/elements/FilterSelectDropdown/index.jsx
> +}
My mistake, I have now removed this file as it shouldn't have been added.

2020-10-12 15:12 UTC, ian-leggett commented on src/client/utils/formatAdviser.js
> +const parseAdviserData = (advisers) => {
Makes sense 👍

2020-10-16 15:08 UTC, ian-leggett commented on src/apps/investments/client/projects/tasks.js
> +      )
This is much better, totally agree.

2020-10-19 09:31 UTC, ian-leggett commented on src/apps/investments/client/projects/tasks.js
> +      ...parsedQuery,
I agree `page` was getting overwritten and was useless but the search will never have `offset` or `limit`. I updated this and removed `page`

2020-10-19 11:02 UTC, ian-leggett commented on src/client/components/CollectionList/CollectionDownload.jsx
> +      href={`${downloadUrl}s/export${decodeURIComponent(search)}`.toLowerCase()}
Removed and this can tackled separately

2020-10-19 11:03 UTC, ian-leggett commented on src/client/components/CollectionList/CollectionDownloadMessage.jsx
> +    )
Removed as we will do this in a separate PR

2020-10-19 15:38 UTC, peterhudec commented on src/client/components/CollectionList/CollectionDownloadMessage.jsx
> +    )
Oh sorry, they are obviously not redundan 🤦

2020-10-20 11:39 UTC, paulgain approved these changes

2020-10-20 14:46 UTC, peterhudec requested changes
Good progress, but I still see a number of issues, mainly how the history/routing related stuff is passed around.

2020-10-21 16:19 UTC, ian-leggett commented on src/apps/investments/client/profiles/LargeCapitalProfileCollection.jsx
> +      payload: { page },
The CollectionList taskProps are checked against a certain object shape for which investment projects include page, filters and a search. I understand that for investment profiles we only have one prop to send as a payload but it was just easier to wrap this in an object to satisfy the validation.

2020-10-21 16:22 UTC, ian-leggett commented on src/apps/investments/client/profiles/state.js
> +export const state2props = (state) => ({ ...state, ...state[ID] })
I do as I need access to the state of the router and that lives outside of the ID specific state of the component.

2020-10-21 16:25 UTC, ian-leggett commented on src/client/utils/omit.js
> +export default omit
Unfortunately this comes up time and time again and Dave strongly mentioned in the PR that we all agreed on removing the use of lodash where we can so I removed it and replaced it with a vanilla option.

2020-10-22 09:58 UTC, mcbhenwood commented on src/apps/investments/client/profiles/LargeCapitalProfileCollection.jsx
> +      payload: { page },
I think in the interests of not over-complicating the CollectionList props declaration (or splitting it into two implementations) we can keep this single-key object here. You're right @peterhudec that this could be simpler for the client coder but I think we should let this one thru.

2020-10-22 10:34 UTC, mcbhenwood commented on src/client/utils/omit.js
> +export default omit
Agreed @peterhudec. Pragmatically speaking (and entirely empirically) we _are_ using lodash and so if we are then we should not duplicate its functionality elsewhere. If we are truly opposed to its use then there needs to be a single piece of work to go through and expunge its implemtation from the codebase entirely which (tbh) I don't see happening.

If there are features of more mature ES versions which supersede lodash bits then yeah for sure we can use those instead but the answer is not to pepper the codebase with "occasionally used' replacements for lodash bits piecemeal.

So let's use `_.omit` as you suggest.

2020-10-26 14:50 UTC, peterhudec requested changes
Almost there, the only required things are:

* Move `<Route>` from `LargeCapitalProfileCollection` to `CollectionList`
* The `advisers` filter should always be an array for simplicity, even when it only has a single adviser.

But I would address the optionals as well. There still are some unadressed issues from the previous review.

2020-10-26 14:50 UTC, peterhudec commented on src/apps/investments/client/projects/state.js
> +  const { adviser = false, sortby = 'created_on:desc', page = 1 } = searchParams
Better do the destructuring right in the params.

2020-10-26 14:50 UTC, peterhudec commented on src/apps/investments/client/projects/state.js
> +    adviser: adviser ? (Array.isArray(adviser) ? adviser : [adviser]) : adviser,
The `adviser` should always be an array for simplicity, even if there's only one adviser. The search param should thus be named `adivesers`.

2020-10-26 14:50 UTC, peterhudec commented on src/apps/investments/client/projects/state.js
> +  return omit(searchParamProps, keysToDelete)
Is this really necessary? If so, then it can be done with just `_.pickBy(searchParamProps, Boolean)`, or with vanilla JS:

```js
return Object.fromEntries(Object.entries(searchParamProps).filter(([_, v]) => v))
```

2020-10-26 14:50 UTC, peterhudec commented on src/apps/investments/transformers/collection.js
> +    headingUrl: urls.investments.projects.details(id),
The name should be `projectDetailUrl` the function doesn't know about any _heading_.

2020-10-26 14:50 UTC, peterhudec commented on src/apps/investments/transformers/collection.js
> +  ]
The badges only have `text` in them, so they should really be just an array of strings.

2020-10-26 14:50 UTC, peterhudec commented on src/client/components/CollectionList/CollectionItem.jsx
> +      <StyledSubheading>{`Project code ${projectCode}`}</StyledSubheading>
Will every collection have a project code?

2020-10-26 14:50 UTC, peterhudec commented on src/client/components/CollectionList/CollectionSort.jsx
> +    <>
Fragment unneccessary

2020-10-26 14:50 UTC, peterhudec commented on src/client/components/CollectionList/index.jsx
> +                    <CollectionItem {...item} key={i} />
Better use some property of `item` ask key.

2020-10-27 11:40 UTC, ian-leggett commented on src/client/components/CollectionList/CollectionItem.jsx
> +      <StyledSubheading>{`Project code ${projectCode}`}</StyledSubheading>
Just removed this you are right

2020-10-27 11:43 UTC, ian-leggett commented on src/apps/investments/transformers/collection.js
> +    headingUrl: urls.investments.projects.details(id),
The collection list collection header component which is shared amongst other areas of the app expects a headingUrl prop so it makes sense for this transformer to return this prop.

2020-10-27 12:35 UTC, ian-leggett commented on src/apps/investments/client/profiles/LargeCapitalProfileCollection.jsx
> +    </Route>
All done, this is now inline with the pattern we created in Projects 👍

2020-10-28 11:06 UTC, ian-leggett commented on src/apps/investments/transformers/collection.js
> +  ]
I assume that they should have had a color prop too but in this case this isn't used so the colour just defaults to grey.

2020-10-28 17:24 UTC, peterhudec approved these changes

2020-10-28 17:32 UTC, merged