Feature/footer
uktrade/data-hub-frontend pull request #2917
Opened 2020-08-27 10:57 UTC by adamledwards

## Description of change

_Document what the PR does and why the change is needed_

## Test instructions

_What should I see?_

## Screenshots
### Before

_Add a screenshot_

### After

_Add a screenshot_

## Checklist

[//]: # "When submitting a PR make sure the code review guidelines have been satisfied.
https://github.com/uktrade/data-hub-frontend/blob/master/docs/Code%20review%20guidelines.md"

- [ ] Has the branch been rebased to master?
- [ ] Automated tests (Any of the following when applicable: Unit, Functional or Acceptance)
- [ ] Manual compatibility testing (Browsers: Chrome, Firefox, IE11, Safari)

2020-09-04 09:06 UTC, rachaelcodes approved these changes

2020-09-11 09:06 UTC, rafenden approved these changes

2020-09-18 11:28 UTC, cgsunkel approved these changes

2020-09-23 13:11 UTC, rachaelcodes commented
Just spotted a visual bug with this: 
<img width="1761" alt="Screenshot 2020-09-23 at 14 10 18" src="https://user-images.githubusercontent.com/23265724/94016872-9b4af200-fda6-11ea-8dbc-13e46adb4f2a.png">

2020-09-23 13:11 UTC, rachaelcodes requested changes
<img width="1761" alt="Screenshot 2020-09-23 at 14 10 18" src="https://user-images.githubusercontent.com/23265724/94016929-adc52b80-fda6-11ea-89d9-d5a35261e55d.png">
Unfortunately, there's a bug that needs fixing

2020-09-29 11:40 UTC, rachaelcodes approved these changes

2020-09-29 14:42 UTC, merged