Toggle component
uktrade/data-hub-frontend pull request #2980
Opened 2020-09-25 13:36 UTC by ian-leggett

## Description of change
This toggle component just toggles visibility of any child elements you wrap it with, this is needed to wrap groups of filters in the new React collection list page that is currently under progress. The design for this can be seen here - https://trade.invisionapp.com/share/VYYV2GMAEW2#/screens/432558396_Investment_Default_Filters

## Test instructions
Go to Storybook - https://uktrade.github.io/data-hub-frontend/ and select the `ToggleSection` component

## Screenshots
![Screenshot 2020-09-25 at 14 27 05](https://user-images.githubusercontent.com/10154302/94273354-34f7d800-ff3c-11ea-80b4-242992339176.png)

## Checklist

[//]: # "When submitting a PR make sure the code review guidelines have been satisfied.
https://github.com/uktrade/data-hub-frontend/blob/master/docs/Code%20review%20guidelines.md"

- [x] Has the branch been rebased to master?
- [x] Automated tests (Any of the following when applicable: Unit, Functional or Acceptance)
- [x] Manual compatibility testing (Browsers: Chrome, Firefox, IE11, Safari)

2020-10-13 09:20 UTC, rachaelcodes commented on src/client/components/ToggleSection/index.jsx
> +    text-decoration: underline;
What do you think about keeping this consistent with other focus styling (e.g. yellow outline/background, grey text: https://design-system.service.gov.uk/styles/colour/ )? I think it might be clearer, for example if people are tabbing through the page on a keyboard on high zoom, as well as being consistent.
(Maybe what we actually need is some sort of focus mixin, but that's maybe a problem for another day!)

2020-10-13 10:43 UTC, rachaelcodes commented on src/client/components/ToggleSection/__stories__/Togglesection.stories.jsx
> +            <FieldInput
Just wondering - is there a reason to have two identical fields?

2020-10-14 13:26 UTC, mforner13 commented on src/client/components/ToggleSection/__stories__/Togglesection.stories.jsx
> +            <FieldInput
Agreed - doesn't seem necessary.

2020-10-14 13:41 UTC, mforner13 requested changes

2020-10-14 13:41 UTC, mforner13 commented on src/client/components/ToggleSection/__stories__/Togglesection.stories.jsx
> +    </>
I worry that having text as the example will be confusing as we are using the gov uk react `Details` component in the rest of DH for toggling text - which also comes with the grey line down the side - making it neater, e.g. on the companies export tab example below. 

Perhaps just having the form element example would prevent any confusion?

![Screenshot 2020-10-14 at 14 30 57](https://user-images.githubusercontent.com/22460823/95995822-e26a5700-0e29-11eb-981c-af6bdb903328.png)

2020-10-14 13:42 UTC, mforner13 commented on src/client/components/ToggleSection/__stories__/Togglesection.stories.jsx
> +    </>
Also adding something to the readme saying for toggling text use the gov uk `Details` component maybe?

2020-10-29 17:26 UTC, ian-leggett commented on src/client/components/ToggleSection/__stories__/Togglesection.stories.jsx
> +    </>
I agree this could be confusing and this shouldn't replace the use case for the details component, I am now only showing the form elements inside the toggle component. After speaking with Mark about the documentation in Storybook I have decided to remove it as I don't think its very useful at this point, its also very easy for this documentation to become stale and out of date as it doesn't get automagically updated when you update the component. Once we have all the new components in and we know exactly how they should be used maybe we can then add some documentation.

2020-10-30 09:34 UTC, ian-leggett commented on src/client/components/ToggleSection/index.jsx
> +    text-decoration: underline;
Good spot, I have updated this as per - https://www.gov.uk/search/all?keywords=search&order=relevance which should be using the correct focus styling

2020-10-30 09:58 UTC, mforner13 approved these changes

2020-10-30 10:09 UTC, rachaelcodes approved these changes

2020-10-30 10:35 UTC, merged