Allow task cancelation and error abortion
uktrade/data-hub-frontend pull request #3043
Opened 2020-10-30 16:30 UTC by peterhudec

## Description of change

This PR allows _tasks_ to be cancelled in their progress and their errors aborted.

## Test instructions

The feature is not used anywhere, but can be seen in action in the storybook under Task -> Cancellation.

2020-11-02 14:47 UTC, ian-leggett commented
Unfortunately I couldn't run this :-( When I fire this up in Storybook I get console errors
![Screenshot 2020-11-02 at 14 46 30](https://user-images.githubusercontent.com/10154302/97881429-4c379b80-1d1a-11eb-8aea-263ba837fb04.png)
It looks like the demo task isn't registered in the root saga file

2020-11-02 15:37 UTC, peterhudec commented
> It looks like the demo task isn't registered in the root saga file. Is this all around allowing the user to retry a call to the backend or stop a current process in the UI?
Oh, sorry, @ian-leggett, seems I have forgot to commit the file where the task is defined.

2020-12-21 11:33 UTC, peterhudec commented
I have Enzyme tests ready for this, but they can't be used since we upgrade to React 17 as [there's not yet an Enzyme adapter for React 17](https://github.com/enzymejs/enzyme/issues/2429).

2021-01-07 14:34 UTC, paulgain commented on src/client/components/Task/reducer.js
> +    : state
Tut-tut... `_.omit` and `_.isEqual`

2021-04-15 10:18 UTC, LaurenQurashi approved these changes
Looks good to me!

2021-04-15 14:58 UTC, elcct approved these changes

2021-04-15 15:24 UTC, ian-leggett requested changes
Can we talk about this PR as I can't run it. Also there are no tests around this work so I am not confident that it won't break anything in the app. The code looks fine, I am just a bit nervous ticking this off without being able to run it.

2021-04-15 17:44 UTC, peterhudec commented
> Can we talk about this PR as I can't run it. Also there are no tests around this work so I am not confident that it won't break anything in the app. The code looks fine, I am just a bit nervous ticking this off without being able to run it.

@ian-leggett the Storybook example should work now that I added the missing file with the task definition. Yeah, the PR it's touching the `Task` mechanism, but we probably have all the code that uses it covered with unit and e2e tests and they are still passing. The cancellation mechanism itself is not tested though. The Enzyme adapter is still not around and probably [never will be](https://github.com/enzymejs/enzyme/issues/2429#issuecomment-820207891), but I could theoretically write tests with [React Testing Library](https://testing-library.com/docs/react-testing-library/intro/) as suggested by the omniscient Dan Abramov.

2021-04-16 12:07 UTC, ian-leggett approved these changes
After our good conversation around this I understand that although ideal, unit testing this would prove to be quite difficult at this stage. I have had a good manual test and as our current tests are green and we need this for a new feature that is being developed I am happy to approve. It would be really good to get some unit testing in place soon, we should get Cypress upgraded to 7 so we can take advantage of the component test runner.

2021-04-16 14:31 UTC, merged