New Chip component
uktrade/data-hub-frontend pull request #3055
Opened 2020-11-02 12:49 UTC by ian-leggett

## Description of change
The Chip component is to be used as filter indicators in the likes of the new React collection lists. 

Note: This is being merged into a feature branch NOT master as its part of the React collection list work.

## Test instructions
1. Run the app and visit the investment project collection page
2. Run storybook and you should see the documentation for it.

## Screenshots
![Screenshot 2020-11-02 at 12 45 16](https://user-images.githubusercontent.com/10154302/97869659-bf84e180-1d09-11eb-8c57-4443c668913e.png)

## Checklist

[//]: # "When submitting a PR make sure the code review guidelines have been satisfied.
https://github.com/uktrade/data-hub-frontend/blob/master/docs/Code%20review%20guidelines.md"

- [x] Has the branch been rebased to master?
- [x] Automated tests (Any of the following when applicable: Unit, Functional or Acceptance)
- [x] Manual compatibility testing (Browsers: Chrome, Firefox, IE11, Safari)

2020-11-02 14:32 UTC, mcbhenwood commented
Yes, I think this is entirely the sort of simple, step-by-step, thin-layer iteration we need to adopt to build out these changes longterm. Thanks @ian-leggett. Not approving because that feels a bit unfair to others since we arrived at these decisions together.

2020-11-03 10:33 UTC, LaurenQurashi approved these changes
Looks good! 🎉 🤠

2020-11-03 10:41 UTC, peterhudec requested changes
Looks good, just a couple of things.

2020-11-03 10:41 UTC, peterhudec commented on src/client/components/AdviserFilterChips/index.jsx
> +      ))}
You are mapping twice, which can be done in a single map.

2020-11-03 10:41 UTC, peterhudec commented on src/client/components/Chip/index.jsx
> +const Chip = ({ label }) => <StyledSpan>{label}</StyledSpan>
I would prefer `children` instead of `label`, it is more idiomatic React. Then you could just export the `StyledSpan`.

2020-11-03 10:41 UTC, peterhudec commented on src/client/components/FilteredCollectionList/FilteredCollectionHeader.jsx
> +          {` ${counterSuffix}`}
No need to wrap it in template string.

2020-11-03 10:41 UTC, peterhudec commented on src/client/components/FilteredCollectionList/index.jsx
> +  selectedAdvisers,
Isn't this too specific? I meand shouldn't the `FilteredCollectionList` be a generic component?

2020-11-03 11:30 UTC, mcbhenwood commented on src/client/components/FilteredCollectionList/index.jsx
> +  selectedAdvisers,
Yep but @peterhudec in this workstream we are employing the Xtreme tactic of only doing the very specific work required for this one story. At the end of this one story / PR there will be a filtered collection list whose only filter is one of Advisers. Hence the naming. If in later work we add other types then we will revisit the structure of the arguments etc.

This may seem crazy but this way of working yields more rapid iterations and makes the structural work an act of refactoring things which already function (rather than developing and architecting all in one move)

2020-11-03 12:01 UTC, ian-leggett commented on src/client/components/FilteredCollectionList/FilteredCollectionHeader.jsx
> +          {` ${counterSuffix}`}
This was done to give space between the number of results and text. I removed it and replaced it with a space in brackets.

2020-11-03 12:02 UTC, ian-leggett commented on src/client/components/AdviserFilterChips/index.jsx
> +      ))}
Good spot, not sure what I was thinking here

2020-11-03 15:07 UTC, peterhudec requested changes
Almost there, just two things.

2020-11-03 15:07 UTC, peterhudec commented on src/client/components/Chip/index.jsx
> +export default Chip
This is equivalent to:
```js
const Chip = StyledSpan
```
But worse, because you are not forwarding the `className`, which will prevent the `Chip` to be further stylable with `styled-components`.

You can just name the styled span `Chip` instead of `StyledSpan` and directly export it. You don't even need to define the prop types as every intrinsic component accepts `children`:

```js
const Chip = styled('span')`
  display: inline-block;
  padding: 12px;
  margin: 4px;
  background-color: ${GREY_3};
  border-radius: ${SPACING.SCALE_2};
`

export default Chip
```

2020-11-03 15:07 UTC, peterhudec commented on src/client/components/FilteredCollectionList/FilteredCollectionHeader.jsx
> +}
We should not use the prehistoric `defaultProps` now that we can use JS's param defaults.

2020-11-03 16:35 UTC, ian-leggett commented on src/client/components/Chip/index.jsx
> +export default Chip
Much nicer thanks 👍

2020-11-03 16:35 UTC, ian-leggett commented on src/client/components/FilteredCollectionList/FilteredCollectionHeader.jsx
> +}
Agreed, forgot that was in there!

2020-11-03 16:37 UTC, peterhudec approved these changes
Immaculate 🥇

2020-11-03 16:48 UTC, merged