Feature/great gov uk forms
uktrade/data-hub-frontend pull request #3117
Opened 2020-12-01 13:27 UTC by paulgain

## Description of change

This piece of work integrates Great.gov.uk forms into Data Hub, initially it's just the `Export enquiry` form, more will be added over time. The new functionality is hidden behind a feature flag, the flag is currently turned on in `dev` and `staging` and off in `prod.` 

It's far easier to read and maintain our own Elasticsearch queries compared to using `bodybuilder ` (an ES query builder) which I've removed due to its inflexibility.

## Test instructions

Bring up the FE locally and point to the dev API on PaaS, then go to: `/companies/6df487c5-7c75-4672-8907-f74b49e6c635/activity` and apply the `All external activity` filter. 

You should see two external activities:

<img width="1033" alt="great gov uk-forms" src="https://user-images.githubusercontent.com/964268/100746604-d5ed8e00-33d8-11eb-9088-581c723ec351.png">

[//]: # "When submitting a PR make sure the code review guidelines have been satisfied.
https://github.com/uktrade/data-hub-frontend/blob/master/docs/Code%20review%20guidelines.md"

- [ ] Has the branch been rebased to master?
- [ ] Automated tests (Any of the following when applicable: Unit, Functional or Acceptance)
- [ ] Manual compatibility testing (Browsers: Chrome, Firefox, IE11, Safari)

2020-12-02 14:39 UTC, ambrozic requested changes

2020-12-02 14:39 UTC, ambrozic commented on src/apps/companies/apps/activity-feed/constants.js
> +  'dit:ServiceDelivery', // Interaction
`ServiceDelivery` instead of `Interaction` or just remove both comments. are not adding anything to context.

2020-12-02 17:17 UTC, paulgain commented on src/apps/companies/apps/activity-feed/constants.js
> +  'dit:ServiceDelivery', // Interaction
Both `dit:Interaction` and `dit:ServiceDelivery` are Interactions (hence the comment). 

**The context lies in the code**
[Here](https://github.com/uktrade/data-hub-frontend/blob/feature/great-gov-uk-forms/src/client/components/ActivityFeed/constants.js#L54) they're grouped. The reason they are grouped is because the [Interaction Component](https://github.com/uktrade/data-hub-frontend/blob/feature/great-gov-uk-forms/src/client/components/ActivityFeed/activities/Interaction.jsx#L27) renders both of them providing the activity type matches one of them.

If the comment is unclear, I can remove them both and add this:
```js
const INTERACTIONS = ['dit:Interaction', 'dit:ServiceDelivery']

const DATA_HUB_ACTIVITY = [
  ...INTERACTIONS,
  'dit:InvestmentProject',
  'dit:OMISOrder',
  'dit:CompanyReferral',
]
```
To me this is the same thing, however, it's just adding superfluous code.

2020-12-02 17:21 UTC, mforner13 commented on src/client/components/ActivityFeed/__fixtures__/index.js
> +import exportAdviceFormFixture from './great_gov_uk_forms/export-enquiry.json'
I think it could be good to refer to it as `exportEnquiryForm...` in-line with the UI to avoid confusion.

2020-12-02 17:22 UTC, paulgain commented on src/client/components/ActivityFeed/__fixtures__/index.js
> +import exportAdviceFormFixture from './great_gov_uk_forms/export-enquiry.json'
Good spot 👍

2020-12-03 08:01 UTC, ambrozic approved these changes

2020-12-03 09:43 UTC, mforner13 approved these changes
Looks great!

2020-12-03 12:44 UTC, merged