Fix TabNav keyboard interaction
uktrade/data-hub-frontend pull request #3349
Opened 2021-02-22 17:19 UTC by peterhudec

## Description of change

Fixes a bug in nested tab `TabNav` components when focus jumped to the inner `TabNav` when using arrow keys to move the focus of the outer `TabNav`.

## Test instructions

1. Go to the homepage `/` or to the [`TabNav` section of the Storybook](https://uktrade.github.io/data-hub-frontend/?path=/story/tabnav--default).
2. Focus the _tablist_ of the outer `TabNav` component
3. Press the right arrow key repeatedly
4. The focus should cycle through all the tabs in the _tablist_ of the outer `TabNav` and should not jump to the inner `TabNav`
5. Move the focus to the inner `TabNav` by hitting the _tab_ key.
6. Press the right arrow key repeatedly
7. The focus should cycle through all the tabs in the _tablist_ of the inner `TabNav` and should not jump to the outer `TabNav`
8. Repeat steps 4 to 7 with the left arrow key.

## Screenshots

There should be no visual change.

2021-02-23 10:30 UTC, ian-leggett requested changes
This seems to work well but I need to know where in the DAC report they point out the issues and what it is they were not happy with. Could you point out where the issues are?

2021-02-23 10:35 UTC, ian-leggett commented on src/client/components/TabNav/index.jsx
> +              tabIndex={-1}
I think we need to remove this as you cannot access the child elements via tab

2021-02-23 12:00 UTC, peterhudec commented on src/client/components/TabNav/index.jsx
> +              tabIndex={-1}
No, the `-1` here makes the focus skip the `tablist`, but jump straight to its tabs, which makes the navigation smoother and is exactly how it works in the [MDN example](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/Tab_Role) this component is based on.

2021-02-23 15:49 UTC, ian-leggett approved these changes

2021-02-24 16:00 UTC, tomkingston approved these changes

2021-05-19 10:56 UTC, merged