WIP: Large capital page framework
uktrade/data-hub-frontend pull request #3386
Opened 2021-03-11 09:33 UTC by PippoRaimondi

## Description of change

_Document what the PR does and why the change is needed_

## Test instructions

_What should I see?_

## Screenshots
### Before

_Add a screenshot_

### After

_Add a screenshot_

## Checklist

[//]: # "When submitting a PR make sure the code review guidelines have been satisfied.
https://github.com/uktrade/data-hub-frontend/blob/master/docs/Code%20review%20guidelines.md"

- [ ] Has the branch been rebased to master?
- [ ] Automated tests (Any of the following when applicable: Unit, Functional or End-to-End)
- [ ] Manual compatibility testing (Browsers: Chrome, Firefox, IE11, Safari)

2021-03-17 13:45 UTC, rachaelcodes commented on src/apps/investments/client/opportunities/Opportunities.jsx
> +const detailsRows = [
Is it worth adding a comment before this to note that it's going to change when the task is added?

2021-03-17 13:52 UTC, rachaelcodes commented on src/apps/investments/client/opportunities/Opportunities.jsx
> +    &nbsp;
Elsewhere, I think we generally use `{' '}` in the React files

2021-03-17 14:48 UTC, peterhudec requested changes
Looks good, but I would not bake in the `Opportunity` specific functionality and terminology into the generic `ButtonLink` and `ToggleSection` components. Instead I would restyle them locally for the specific use cases.

2021-03-17 14:48 UTC, peterhudec commented on src/apps/investments/client/opportunities/Opportunities.jsx
> +      id="TabNav"
The `id` should be something which uniquely identifies this particular instance of the `TabNav`, ideally so that it would be obvious where the `TabNav` is used when looking at it's state in Redux dev-tools e.g `"Opportunities"`. Basically, the state of this particular instance of the `TabNav` is stored in the redux store under the ID. 
Two tab navs with the same id would work in sync.
```js
const state = {
  TabNav: {
    'some-id': {focusIndex: 'foo', selectedIndex: 'bar'},
    'some-other-id': {focusIndex: 'ham', selectedIndex: 'spam'},
    // Here it's obvious from the id,
    // that it's a state of the TabNav used in the Opportunities component
    Opportunities: {focusIndex: 'details', selectedIndex: 'details'},
   },
}
```

2021-03-17 14:48 UTC, peterhudec commented on src/apps/investments/client/opportunities/Opportunities.jsx
> +                id="toggle_details"
The same as in my comment above applies to the ids here. It should be something like `"Opportunities.details"`.

2021-03-17 14:48 UTC, peterhudec commented on src/apps/investments/client/opportunities/Opportunities.jsx
> +                id="toggle_requirements"
Should be `id="Opportunities.requirements"`

2021-03-17 14:48 UTC, peterhudec commented on src/apps/investments/client/opportunities/Opportunities.jsx
> +      id="toggle_delete"
Should be `id="Opportunity.delete"`

2021-03-17 14:48 UTC, peterhudec commented on src/apps/investments/client/opportunities/Opportunities.jsx
> +    &nbsp;
Not sure why `&nbsp;` is needed here. The `TabNav` and `ToggleSections` should be `display: block` elements. If it is for the spacing, we should use CSS.

2021-03-17 14:48 UTC, peterhudec commented on src/apps/investments/controllers/opportunities.js
> +const renderOpportunitiesView = async (req, res, next) => {
It probably doesn't need to be `async`, although it doesn't do any harm.

2021-03-17 14:48 UTC, peterhudec commented on src/client/components/ButtonLink/index.jsx
> +    ${(props) => props.float && `float: ${props.float};`}
We should not bake case specific logic int to this kind of generic components. A better approach is to re-style the `ButtonLink` in the component where the special case is needed:

```js
const FloatingButtonLink = styled(ButtonLink)({
  folat: 'right',
})
```

2021-03-17 14:48 UTC, peterhudec commented on src/client/components/ToggleSection/index.jsx
> +  isStatic = false,
These props are too coupled to the specific case of the `Opportunities` component. The `ToggleSection` is a pretty generic component used in at least two other places where there's no notion of a _field_. I would instead just add a single `subtitle` or `sublabel` prop which would accept any content and render it on the right side of the heading.

Also it is not clear what _static_ means here. It only seems to affect the font size. Instead of introducing this property, I would restyle the `ToggleSection` where the decreased font size is needed.

2021-03-17 14:48 UTC, peterhudec commented on src/client/components/ToggleSection/index.jsx
> +}
Simila as in the `ButtonLink` above, this is too specific to be in a generic component like this. I would move the whole thing out of here and pass it as a `subtitle` prop as explained in my comment below.

2021-03-17 14:48 UTC, peterhudec commented on src/client/components/ToggleSection/index.jsx
> +    {renderRequiredFields(showRequiredField, fieldCount)}
It's slightly more performant (although negligible here) to shape the signature of functions like this as components and delegate calling of them to React by using them as components. e.g. `<RequiredFields showRequiredField={showRequiredField} fieldCount={fieldCount}/>`. That way, the function will only be called if one of the values changes.

2021-03-18 10:10 UTC, PippoRaimondi commented on src/apps/investments/client/opportunities/Opportunities.jsx
> +const detailsRows = [
good one, will do!

2021-03-18 13:33 UTC, PippoRaimondi commented on src/apps/investments/controllers/opportunities.js
> +const renderOpportunitiesView = async (req, res, next) => {
might as well remove so it doesn't mislead a possible debug on this feature.

2021-03-22 11:01 UTC, rachaelcodes approved these changes

2021-03-22 15:49 UTC, peterhudec approved these changes
Looks good, just one little suggestion about optimizing the `renderRequiredFields` for React performance.

2021-03-22 15:49 UTC, peterhudec commented on src/apps/investments/client/opportunities/Opportunities.jsx
> +              {renderRequiredFields(incompleteRowsCount(requirementsRows))}
It's better from the performance perspective to have the `renderRequiredFields` as a React component and not just a function call. That way it would only be called when `requirementsRows` changes.

```jsx

</ToggleSection>
{/* Will only be called if  requirementsRows changes */}
<RequiredFields rows={requirementsRows}/>
{/* Will be called on every render */}
{renderRequiredFields(incompleteRowsCount(requirementsRows))}
<ToggleSection
  variant={VARIANTS.SECONDARY}
  label="Opportunity requirements"
  id="opportunity_requirements_toggle"
>
```

2021-03-23 10:12 UTC, merged