Add UK Opportunities CollectionList page to investments app
uktrade/data-hub-frontend pull request #3481
Opened 2021-04-16 15:33 UTC by LaurenQurashi

## Description of change

This PR adds the third tab to the investments app, which displays UK opportunities. This PR doesn't include adding filters or download functionality to this tab. This tab shows a collection list of the UK opportunities with MVP metadata and location badges, as well as a button in the header to link to existing functionality to create a new opportunity. 

## Test instructions

_What should I see?_

## Screenshots
### Before

_Add a screenshot_

### After

_Add a screenshot_

## Checklist

[//]: # "When submitting a PR make sure the code review guidelines have been satisfied.
https://github.com/uktrade/data-hub-frontend/blob/master/docs/Code%20review%20guidelines.md"

- [ ] Has the branch been rebased to master?
- [ ] Automated tests (Any of the following when applicable: Unit, Functional or End-to-End)
- [ ] Manual compatibility testing (Browsers: Chrome, Firefox, IE11, Safari)

2021-04-21 14:13 UTC, LaurenQurashi commented on src/apps/investments/client/opportunities/UnfilteredLargeCapitalOpportunityCollection.jsx
> +      addItemUrl="/investments/opportunities/create"
Not sure what to do about this. The code that handles pluralising depending on list length just adds an S to the end of the entity name if there's more than one and I'm not sure what logic is bet to implement the prevention of this.

2021-04-22 08:54 UTC, LaurenQurashi commented on src/apps/investments/client/opportunities/LargeCapitalOpportunityCollection.jsx
> +export default ({ ...props }) => <Unfiltered {...props} />
Here I'm creating a holder component. The Profiles tab seemed to follow the same convention - it checks for a flag present and depending on the flag it would either show the unfiltered version or the filtered version. Filters will be added in another ticket so for now the component just shows the unfiltered version.

2021-04-22 09:03 UTC, LaurenQurashi commented on src/apps/investments/client/opportunities/state.js
> +export const ID = 'opportunitiesList'
Wasn't too sure about this either. I found it tricky to figure out what exactly this ID allows stuff to do? The profiles tab has a similar set up to the Opportunities tab and a lot of the patterns were copied for this. Profiles seemed to also only have one ID called `profilesList` but it is the only id available in the state for all their tasks. Is there a convention to naming this ID? I'm not sure whether it's right that the tasks in the opportunities details page also uses this ID? 🤷‍♀️

2021-04-22 09:10 UTC, LaurenQurashi commented on src/apps/investments/controllers/opportunities.js
> +module.exports = { renderOpportunitiesView, renderOpportunityDetailsView }
Here I accidentally changed the original Details view controller to show the List view instead, then realised that was a silly thing to do as it broke the old Details view, so made a new one. This is what the controller for the list view looks like. 

```
const renderOpportunitiesView = (req, res, next) => {
  try {
    res
      .breadcrumb('UK Opportunities')
      .render('investments/views/opportunities', {
        heading: 'UK Opportunities',
        props: {
          opportunityId: req.params.opportunityId,
        },
      })
  } catch (error) {
    next(error)
  }
}
```

2021-04-22 09:17 UTC, LaurenQurashi commented on src/apps/investments/transformers/opportunities.js
> +    return locationBadgeText
If there's a better way to do this please let me know! I struggled to get a more concise version to work but I would be grateful for any refactoring offered up on this! 😄

2021-04-22 09:20 UTC, LaurenQurashi commented on src/apps/investments/views/opportunities.njk
> +</div>
Just copying the profile tab set up for the nunjucks that holds the react component.

2021-04-22 09:20 UTC, LaurenQurashi commented on src/apps/investments/views/opportunity-details.njk
> +{% endblock %}
When I created the Opportunities tab, I overwrote the details tab stuff, so had to make a new one once I realised.

2021-04-22 09:21 UTC, LaurenQurashi commented on src/client/components/CollectionList/CollectionHeader.jsx
>      >
I added this data-test attribute so that I can grab the button in the functional Cypress tests

2021-04-22 09:23 UTC, LaurenQurashi commented on src/client/components/CollectionList/index.jsx
> +            addItemUrl={addItemUrl}
The CollectionHeader already had the ability to take this attribute, but the CollectionList component was just missing the functionality to pass it down. I added it as I needed the Add Opportunities button.

2021-04-22 13:11 UTC, LaurenQurashi commented on src/apps/investments/client/opportunities/UnfilteredLargeCapitalOpportunityCollection.jsx
> +      entityName="opportunitie"
Not sure what to do about this. The code that handles pluralising depending on list length just adds an S to the end of the entity name if there's more than one and I'm not sure what logic is best to implement the prevention of this.

2021-04-22 13:12 UTC, LaurenQurashi commented on src/client/components/CollectionList/CollectionHeader.jsx
> +      data-test="add-item-url-button"
I added this data-test attribute so that I can grab the button in the functional Cypress tests.

2021-04-22 13:17 UTC, LaurenQurashi commented on test/visual/specs/data-hub-pages-spec.js
> +    await filter.waitForDisplayed({ timeout: 10000 })
Pippo and I added this to force the tests to wait for the filters to load and then take the screenshots. This is because it would regularly fail by taking a screenshot too quickly and then complain that there's no stuff on the page

2021-04-22 14:00 UTC, ian-leggett requested changes

2021-04-22 14:00 UTC, ian-leggett commented on src/apps/investments/client/opportunities/UnfilteredLargeCapitalOpportunityCollection.jsx
> +  const collectionListTask = {
If there is only one use case I would just inline this into line 30

2021-04-22 14:00 UTC, ian-leggett commented on src/apps/investments/client/opportunities/LargeCapitalOpportunityCollection.jsx
> +export default ({ ...props }) => <Unfiltered {...props} />
I can't see why we need this file. The profile tab uses a ternary whereas yours just imports one file, renames it and forwards the props onto the renamed component. We can remove this file and just export one instead.

2021-04-22 14:00 UTC, ian-leggett commented on src/apps/investments/client/opportunities/state.js
> +export const ID = 'opportunitiesList'
This is important so all the state changes that relate to this feature fall under one id and not just spread on the root which could quite easily have some very strange effects to the UI. I can demo this to you if you like 👍

2021-04-22 14:00 UTC, ian-leggett commented on src/apps/investments/transformers/opportunities.js
> +const { investments } = require('../../../lib/urls')
We need to remove this file, we can't really do anymore data transformation in this layer as we are moving towards a client side app. We can apply some of this logic in the React layer.

2021-04-22 14:00 UTC, ian-leggett commented on src/apps/investments/transformers/opportunities.js
> +    return locationBadgeText
See my comment above 👍

2021-04-22 14:00 UTC, ian-leggett commented on src/client/components/CollectionList/CollectionHeader.jsx
> +      data-test="add-item-url-button"
We should lift this test hook higher up to the root of the collection header as you want to test wether this button renders within the context of the component.

2021-04-22 14:00 UTC, ian-leggett commented on test/functional/cypress/specs/investments/investment-opportunity-details.js
> +    cy.get('#opportunity-details').should('contain', 'Complete')
We can't use id's here we need to use data attributes such as `data-test`

2021-04-22 14:00 UTC, ian-leggett commented on test/functional/cypress/specs/investments/investment-opportunity-details.js
> +    cy.get('#opportunity-details').should('contain', '3 fields required')
We can't use id's here we need to use data attributes such as `data-test`

2021-04-23 11:41 UTC, LaurenQurashi commented on test/functional/cypress/specs/investments/investment-opportunity-details.js
> +    cy.get('#opportunity-details').should('contain', 'Complete')
Will add this change into the current outstanding PR around the opportunities details page! 🎉

2021-04-27 14:37 UTC, faissalMT approved these changes
Just one minor issue but nothing that's a showstopper as far as I can tell

2021-04-27 14:37 UTC, faissalMT commented on src/apps/investments/client/opportunities/Details/reducer.js
> +      return state
This pattern appears in a few places in this PR, unless you intend to expand this in future it might be clearer to represent this as a conditional return. I usually go by the rule of thumb that if I have less than 7 conditions I don't use a `switch`.

2021-04-27 15:49 UTC, LaurenQurashi commented on src/apps/investments/client/opportunities/Details/reducer.js
> +      return state
Thank you so much for the review! That's a good point, I think in the next PR I'm going to be making it will be expanding, however, I'm not sure if it's more than 7 conditions so I'll swap it out for a conditional 😎 Thanks!

2021-04-28 12:43 UTC, ian-leggett commented on src/apps/investments/client/opportunities/List/UnfilteredLargeCapitalOpportunityCollection.jsx
> +  return (
We can use an implicit return here

2021-04-28 12:49 UTC, ian-leggett commented on src/apps/investments/client/opportunities/List/tasks.js
> +      return data
I would remove line 37 and just return 
```
{
        count: data.count,
        results: data.results.map(transformInvestmentOpportunitiesList),
      }
```

2021-04-28 12:50 UTC, ian-leggett commented on src/client/components/DownloadDataHeader/__stories__/DownloadDataHeader.stories.jsx
> +  return (
We can use an implicit return here

2021-04-28 14:18 UTC, ian-leggett approved these changes

2021-04-28 14:56 UTC, merged