WIP! Feature/add opportunity detail forms
uktrade/data-hub-frontend pull request #3540
Opened 2021-05-06 11:13 UTC by LaurenQurashi

## Description of change

_Document what the PR does and why the change is needed_

## Test instructions

_What should I see?_

## Screenshots
### Before

_Add a screenshot_

### After

_Add a screenshot_

## Checklist

[//]: # "When submitting a PR make sure the code review guidelines have been satisfied.
https://github.com/uktrade/data-hub-frontend/blob/master/docs/Code%20review%20guidelines.md"

- [ ] Has the branch been rebased to master?
- [ ] Automated tests (Any of the following when applicable: Unit, Functional or End-to-End)
- [ ] Manual compatibility testing (Browsers: Chrome, Firefox, IE11, Safari)

2021-05-20 08:59 UTC, tomkingston reviewed
Hi Lauren - left a few comments. My main query is on why you are nesting everything under `details` rather than using the old pattern which appears to be a bit simpler?

It looks like the commits could also be tidied up a bit to avoid WIP / fix up commit messages.

2021-05-20 08:59 UTC, tomkingston commented on src/apps/investments/client/opportunities/Details/Opportunities.jsx
> +            variant={VARIANTS.SECONDARY}
Once you rebase, you will be able to get rid of the variants (the default variant is the same so just import ToggleSection)

2021-05-20 08:59 UTC, tomkingston commented on src/apps/investments/transformers/opportunities.js
> +const idName2valueLabel = ({ id, name }) => ({ value: id, label: name })
The casing on this looks a bit strange - shouldn't it be `idName2ValueLabel`... or even better `idNameToValueLabel`

2021-05-20 08:59 UTC, tomkingston commented on src/apps/investments/client/opportunities/Details/tasks.js
> +const idName2valueLabel = ({ id, name }) => ({ value: id, label: name })
As before, the casing on this looks a bit strange - `idNameToValueLabel` would be best

2021-05-20 12:06 UTC, LaurenQurashi commented on src/apps/investments/client/opportunities/Details/reducer.js
> +        details: { ...transformInvestmentOpportunityDetails(result) },
spoke on slack - Details is nested due to the final wireframe having 5 tabs, details being one of them, decided to keep the nesting 😎

2021-05-20 12:22 UTC, peterhudec requested changes
Getting there, but there are some issues. Although not introduced by this PR, but heavily affecting it is the massive reducer. It's tightly coupling all the components together. It needs to be broken down into smaller reducers owned by the respective sub-components.

2021-05-25 12:54 UTC, peterhudec commented
The form seems to work fine in that it updates the name, but there is a slight UX defficiency:

When the form is submitted, the user is returned back to the read only view, which however is still showing the old name. The user must refresh the page to see the updated name.

2021-05-27 08:28 UTC, merged