Update address form to include state for US companies.
uktrade/data-hub-frontend pull request #3623
Opened 2021-06-03 10:56 UTC by ccp92

## Description of change

_Document what the PR does and why the change is needed_

## Test instructions

_What should I see?_

## Screenshots
### Before

_Add a screenshot_

### After

_Add a screenshot_

## Checklist

[//]: # "When submitting a PR make sure the code review guidelines have been satisfied.
https://github.com/uktrade/data-hub-frontend/blob/master/docs/Code%20review%20guidelines.md"

- [ ] Has the branch been rebased to master?
- [ ] Automated tests (Any of the following when applicable: Unit, Functional or End-to-End)
- [ ] Manual compatibility testing (Browsers: Chrome, Firefox, IE11, Safari)

2021-06-09 10:00 UTC, cgsunkel approved these changes

2021-06-15 09:16 UTC, ian-leggett commented on src/client/components/Form/elements/FieldAddress/index.jsx
> +  const [canadaProvinces, setCanadaProvinces] = useState([])
Should this be in a generic component?

2021-06-15 09:18 UTC, ian-leggett requested changes
It looks as if we have business logic inside a generic component. We should pass this down to the component and not bake it in

2021-06-15 09:20 UTC, ian-leggett approved these changes

2021-06-15 09:35 UTC, paulgain commented on src/client/components/Form/elements/FieldAddress/index.jsx
> +      const result = await axios('/api-proxy/v4/metadata/administrative-area')
I think we need to be consistent and follow the same pattern as `usePostcodeLookup `.

2021-06-23 11:35 UTC, vfarah-if commented on src/client/components/Form/elements/FieldAddress/index.jsx
> +      const result = await axios('/api-proxy/v4/metadata/administrative-area')
Fixed, thanks Paul

2021-06-23 12:47 UTC, tomkingston approved these changes

2021-06-25 09:31 UTC, merged