Add Postcode Validation to postcode field when country is United States or Canada
uktrade/data-hub-frontend pull request #3898
Opened 2021-08-12 14:47 UTC by ccp92

## Description of change

This PR adds front-end validation to the add/edit company form to mark Postcode as a mandatory field when the country is United States or Canada

## Test instructions

Go to add a new company/ edit an existing company that has a country set as United States or Canada.
If you attempt to submit the form without completing the postcode field, the field should be highlighted with an error message.

## Screenshots
### Before

![image](https://user-images.githubusercontent.com/20663545/129217768-dc7a47ae-f158-4d5c-9590-7f9967da62f2.png)

### After

![image](https://user-images.githubusercontent.com/20663545/129217685-ffa20a60-4473-4907-9f51-9fadcd98bb8c.png)

## Checklist

[//]: # "When submitting a PR make sure the code review guidelines have been satisfied.
https://github.com/uktrade/data-hub-frontend/blob/master/docs/Code%20review%20guidelines.md"

- [ ] Has the branch been rebased to master?
- [ ] Automated tests (Any of the following when applicable: Unit, Functional or End-to-End)
- [ ] Manual compatibility testing (Browsers: Chrome, Firefox, IE11, Safari)

2021-08-12 16:07 UTC, mforner13 requested changes

2021-08-12 16:07 UTC, mforner13 commented on src/client/components/Form/elements/FieldAddress/index.jsx
> +    if (isCanada) return 'Postal Code is required'
The common pattern for errors for a text input field is `Enter a <thing you're asking for>` 

So I think these should be `Enter a zip code` and `Enter a postal code`.

Guidance on error messages in the design system [here](https://design-system.service.gov.uk/components/error-message/).

In other places in this form it misses out the 'a' which definitely seems grammatically incorrect :p e.g. `Enter town or city` and `Enter postcode`, so if you've got a content designer on hand could check if they're cool with us updating the others.

2021-08-13 09:53 UTC, chloehkwong1 commented on src/client/components/Form/elements/FieldAddress/index.jsx
> +    if (isCanada) return 'Postal Code is required'
@mforner13 thanks for this! We'll look into updating the others at the same time :)

2021-08-17 13:57 UTC, mforner13 approved these changes

2021-08-18 11:16 UTC, merged