Navigate events using react router mostly
uktrade/data-hub-frontend pull request #4190
Opened 2021-12-03 13:56 UTC by vfarah-if

## Description of change

Test react router and events where there should only be one server side request and all functionality should work like it used to

## Test instructions

Working with local reloads like before

## Screenshots
### Before

_Add a screenshot_

### After

_Add a screenshot_

## Checklist

[//]: # "When submitting a PR make sure the code review guidelines have been satisfied.
https://github.com/uktrade/data-hub-frontend/blob/master/docs/Code%20review%20guidelines.md"

- [ ] Has the branch been rebased to master?
- [ ] Automated tests (Any of the following when applicable: Unit, Functional or End-to-End)
- [ ] Manual compatibility testing (Browsers: Chrome, Firefox, Edge, Safari)

2021-12-06 11:46 UTC, vfarah-if commented on src/client/modules/Events/EventDetails/index.jsx
> +      {() => {
Remove the brace once the flashMessage details have been resolved

2021-12-06 12:04 UTC, vfarah-if commented on src/client/modules/Events/EventDetails/index.jsx
> +  // const state = undefined
Remove when done

2021-12-07 08:44 UTC, tomkingston commented on src/apps/events/controllers/events.js
> +const renderReactifiedEventsView = async (req, res, next) => {
Since this will remain the only events view I think you should just leave this as `renderEventsView` to avoid any confusion.

2021-12-07 08:47 UTC, tomkingston commented on src/client/modules/Events/EventDetails/tasks.js
> +export const getEventSummaryDetails = (eventId) =>
Why is this now called `getEventSummaryDetails` - why not keep it as `getEventDetails`? The api endpoint doesn't suggest this is any different to standard event details. (Same for the related task names etc).

2021-12-07 08:51 UTC, tomkingston commented on src/client/modules/Events/EventForm/EventFormFields.jsx
> +  return (
One of Ian's favourite PR comments was always to make these implicit returns (ie `export const EventFormFields = ({ values }) => (<>...</>)`... however, that does mean changing all the indentation as soon as you want to do a bit more than that in the future, so I'm not bothered either way.

2021-12-07 08:54 UTC, tomkingston commented on src/client/modules/Events/EventForm/__stories__/EventForm.stories.jsx
>    .add('Edit event', () => (
I don't think the EventForm should really be in storybook which is I would expect to be reserved for re-usable components rather than 'modules' - storybook could end up quite cluttered with all the modules.... if you do want it, perhaps you could add it to a `modules` namespace so that it doesn't appear with all the components etc.

2021-12-07 09:17 UTC, tomkingston commented
Noticed this when clicking through to an event....
![image](https://user-images.githubusercontent.com/1234577/145000885-b41b2a83-54f9-4062-8107-bc496ee56cce.png)
The header / layout etc should stay visible after the click.

2021-12-07 10:45 UTC, vfarah-if commented on src/client/modules/Events/EventDetails/tasks.js
> +export const getEventSummaryDetails = (eventId) =>
This is ambiguous with EventDetails in another space and seemed clearer to understand because it is event collection, event summary, event details so this helped to make a clear difference between the two

2021-12-07 10:47 UTC, vfarah-if commented on src/client/modules/Events/EventForm/__stories__/EventForm.stories.jsx
>    .add('Edit event', () => (
Okay cool I will move it to Modules. I liked this because it is an isolated space for doing this in a standalone environment and is a good example for doing this,

2021-12-07 14:31 UTC, vfarah-if commented on src/client/modules/Events/EventForm/EventFormFields.jsx
> +  return (
Fixed to follow standard

2021-12-07 14:35 UTC, vfarah-if commented on src/apps/events/controllers/events.js
> +const renderReactifiedEventsView = async (req, res, next) => {
The main reason for this is to move this out and share it for all things that use react as this will be the same default template going forward, but no problem I can put that the way it was

2021-12-07 18:21 UTC, vfarah-if commented on src/client/modules/Events/EventDetails/tasks.js
> +export const getEventSummaryDetails = (eventId) =>
Rolledback

2021-12-08 09:13 UTC, tomkingston approved these changes

2021-12-08 13:53 UTC, paulgain approved these changes
I really don't like the idea of passing `useReactRouter` down the collection list, I also understand that we're moving from one tech stack to another, I guess we'll have to swallow this until everything has migrated across at which point we'll have an SPA and can then remove the conditionals currently going in.

2021-12-08 16:49 UTC, paulgain requested changes
**Just come across this issue when adding an attendee to an event**

<img width="1344" alt="unable-to-add-attendee" src="https://user-images.githubusercontent.com/964268/145248962-36eb2a2a-de07-4e1f-9f8f-f38d60260ad3.png">

2021-12-13 12:16 UTC, mforner13 commented on src/client/components/Task/Form/index.jsx
> +                                              { messages: getMessages() }
Could you just use the message that's been passed in on the flashMessage prop from line 210 here, rather than calling session storage? I.e:
`{messages: message}`

2021-12-13 12:16 UTC, mforner13 commented on src/client/modules/Events/EventForm/index.js
> +import React from 'react'
Seems like this file was accidentally turned to `.js` from `.jsx`

2021-12-13 12:29 UTC, vfarah-if commented on src/client/components/Task/Form/index.jsx
> +                                              { messages: getMessages() }
I was worried about throwing away other potential message, so to guarantee this does not happen, I take it from the queue that can be generated from other tabs or stuff

2021-12-13 14:03 UTC, mforner13 approved these changes
Looks good pending Paul's approval :)

2021-12-13 16:01 UTC, paulgain approved these changes

2021-12-13 16:15 UTC, merged