WIP: 301 - Replace MultiInstanceForm with TaskForm
uktrade/data-hub-frontend pull request #4221
Opened 2021-12-14 11:27 UTC by michalk01

## Description of change

Replace instances of MultiInstanceForm with TaskForm

## Test instructions

_What should I see?_

## Screenshots
### Before

_Add a screenshot_

### After

_Add a screenshot_

## Checklist

[//]: # "When submitting a PR make sure the code review guidelines have been satisfied.
https://github.com/uktrade/data-hub-frontend/blob/master/docs/Code%20review%20guidelines.md"

- [ ] Has the branch been rebased to master?
- [ ] Automated tests (Any of the following when applicable: Unit, Functional or End-to-End)
- [ ] Manual compatibility testing (Browsers: Chrome, Firefox, Edge, Safari)

2021-12-14 11:56 UTC, faissalMT commented on src/apps/investments/views/admin/client/InvestmentProjectAdmin.jsx
> +            </FormActions>
`<FormActions/>` were moved into `<TaskForm/>` too via the `actionLinks` prop, the save button dosen't have to be moved since it's there by default, just the cancel

2021-12-14 12:01 UTC, faissalMT commented on src/apps/investments/views/admin/client/InvestmentProjectAdmin.jsx
> +            submissionTaskName={TASK_UPDATE_STAGE}
For this submission task to work you'll need to make sure it recieves the data it needs. You can push data to the task via `transformPayload`, for example here we want to make the task has the `projectId` in addition to the payload so you would have something like `transformPayload={(values) => ({...values, projectId})}`

2021-12-14 12:08 UTC, faissalMT commented on src/apps/my-pipeline/client/ArchivePipelineItemForm.jsx
Ticket CI-304, is only for working on `InvestmentProjectAdmin`. Since other people are working on tickets for these files, or might be assigned to them, changing them is just additional work that will cause conflicts

2021-12-15 14:21 UTC, cgsunkel reviewed
I have a few minor comments for now, let me know when all the tests are passing and I'll have another look.

Also would you mind updating the PR title and body to be more descriptive of what's been changed?

2021-12-15 14:21 UTC, cgsunkel commented on src/apps/investments/views/admin/client/InvestmentProjectAdmin.jsx
> +            analyticsFormName="investment-project-admin"
```suggestion
            analyticsFormName="investmentProjectAdmin"
```

The performance analysts have asked us to have this in snake case

2021-12-15 14:21 UTC, cgsunkel commented on src/apps/investments/views/admin/client/InvestmentProjectAdmin.jsx
>      <Task>
This `<Task>` shouldn't be required anymore

2021-12-15 14:21 UTC, cgsunkel commented on src/apps/investments/views/admin/client/InvestmentProjectAdmin.jsx
> +                children: 'Save',
```suggestion
                children: 'Cancel',
```

The text for this link should be 'Cancel'

2021-12-15 14:39 UTC, mforner13 requested changes
In addition to the comments, you can remove the reducer.js and state.js files from this folder now they're no longer being used (can just replace `STATE_ID` on the id prop in Taskform with a string) and also remove `INVESTMENT_PROJECT_ADMIN__UPDATE_STAGE` from the `src/client/actions.js` file :)

Let me know if you want to talk through anything!

2021-12-15 14:39 UTC, mforner13 commented on src/apps/investments/views/admin/client/InvestmentProjectAdmin.jsx
> +            transformPayload={(values) => ({ ...values, projectId })}
Spreading `values` here breaks the task which submits this data to the api, as in there it destructures `values` from its arguments and calls values.projectStageId ([code here](https://github.com/uktrade/data-hub-frontend/blob/master/src/apps/investments/views/admin/client/tasks.js#L8)). If you just pass `({ values, projectId })` it should work :)

2021-12-15 14:39 UTC, mforner13 commented on src/apps/investments/views/admin/client/InvestmentProjectAdmin.jsx
>  }
Sorry It won't let me make this comment on the exact line - but as you're not connecting this component to the redux store, you can remove the connect function from the export at the bottom of the file and just have
`export default InvestmentProjectAdmin`

2021-12-16 11:38 UTC, cgsunkel approved these changes

2021-12-16 11:43 UTC, mforner13 approved these changes
Looks good 👍

2021-12-16 11:57 UTC, merged