Upgrade Node from 16.15.1 to 16.16.0
uktrade/data-hub-frontend pull request #4758
Opened 2022-07-22 16:56 UTC by vfarah-if

## Description of change

Try fix up NPM warnings

## Test instructions

Application should work as before

## Checklist

[//]: # "When submitting a PR make sure the code review guidelines have been satisfied.
https://github.com/uktrade/data-hub-frontend/blob/master/docs/Code%20review%20guidelines.md"

- [ ] Has the branch been rebased to master?
- [ ] Automated tests (Any of the following when applicable: Unit, Functional or End-to-End)
- [ ] Manual compatibility testing (Browsers: Chrome, Firefox, Edge, Safari)

2022-07-26 14:09 UTC, marijnkampf approved these changes

2022-07-26 14:21 UTC, Harriethw approved these changes

2022-07-26 15:29 UTC, cgsunkel requested changes
I would hold back on merging this for the moment as we can't be certain that this won't cause breaking changes in production.

2022-07-28 15:33 UTC, cgsunkel approved these changes

2022-07-28 20:19 UTC, merged