Feature/det 269 aventri id filter
uktrade/data-hub-frontend pull request #4904
Opened 2022-09-14 14:05 UTC by santoshdasa12345

## Description of change

New Aventri ID search filter has been added

## Test instructions

New Aventri ID Search Filter has been added
Added Hint text with validations

## Screenshots

### Before

<img width="1008" alt="image" src="https://user-images.githubusercontent.com/74972011/190348102-7ab7a420-2974-4101-afce-5889a96fe92c.png">

### After

![image](https://user-images.githubusercontent.com/74972011/190348238-b9cb99ce-f915-4c7b-97f6-496a82028105.png)

## Checklist

[//]: # 'When submitting a PR make sure the code review guidelines have been satisfied.
https://github.com/uktrade/data-hub-frontend/blob/main/docs/Code%20review%20guidelines.md'

- [x] Has the branch been rebased to main?
- [x] Automated tests (Any of the following when applicable: Unit, Functional or End-to-End)
- [ ] Manual compatibility testing (Browsers: Chrome, Firefox, Edge, Safari)

2022-09-15 08:51 UTC, chloehkwong1 requested changes

2022-09-15 08:51 UTC, chloehkwong1 commented on test/functional/cypress/specs/events/filter-spec.js
> +        it('should allow 9 digits', () => {
Maybe the following test message would be a bit more descriptive? :) 
```suggestion
        it('should truncate any long numbers to 9 digits', () => {
```

2022-09-15 08:51 UTC, chloehkwong1 commented on test/functional/cypress/specs/events/filter-spec.js
> +      const invalidAventriId = 'Testing'
Maybe add a space and a symbol on the end just to double check it is not allowing those too!
```suggestion
      const invalidAventriId = 'Testing %'
```

2022-09-15 08:51 UTC, chloehkwong1 commented on test/functional/cypress/specs/events/filter-spec.js
> +        it('should aventri ID from user input to query param', () => {
```suggestion
        it('should add an aventri ID from user input to query param', () => {
```

2022-09-15 08:51 UTC, chloehkwong1 commented on test/functional/cypress/specs/events/filter-spec.js
> +          cy.get(element).type(`${invalidAventriId}{enter}`)
You should probably check the filter is empty here, and to check nothing as been added to the query params :)

2022-09-15 08:51 UTC, chloehkwong1 commented on test/functional/cypress/specs/events/filter-spec.js
> +    context('Aventri ID', () => {
We should also add in a test to check the express route on the activity feed controller is working correctly (let me know when you get to this stage and I can help!)

2022-09-15 13:32 UTC, santoshdasa12345 commented on test/functional/cypress/specs/events/filter-spec.js
> +          cy.get(element).type(`${invalidAventriId}{enter}`)
Added assertion for the test

2022-09-16 07:52 UTC, santoshdasa12345 commented on test/functional/cypress/specs/events/filter-spec.js
> +    context('Aventri ID', () => {
Add tests

2022-09-16 12:15 UTC, richmadetech approved these changes

2022-09-20 10:59 UTC, onyela-o approved these changes

2022-09-20 12:06 UTC, chloehkwong1 approved these changes

2022-09-20 14:01 UTC, merged