Chore/dependencies 2022 10 31
uktrade/data-hub-frontend pull request #5017
Opened 2022-10-31 11:40 UTC by dredmonds

## Description of change

_Document what the PR does and why the change is needed_

## Test instructions

_What should I see?_

## Screenshots

### Before

_Add a screenshot_

### After

_Add a screenshot_

## Checklist

[//]: # 'When submitting a PR make sure the code review guidelines have been satisfied.
https://github.com/uktrade/data-hub-frontend/blob/main/docs/Code%20review%20guidelines.md'

- [ ] Has the branch been rebased to main?
- [ ] Automated tests (Any of the following when applicable: Unit, Functional or End-to-End)
- [ ] Manual compatibility testing (Browsers: Chrome, Firefox, Edge, Safari)

2022-10-31 12:15 UTC, cgsunkel requested changes

2022-10-31 12:15 UTC, cgsunkel commented on package.json
> +    "@sentry/browser": "^7.17.2",
The other Sentry/Storybook dependencies need to be updated as well - there are two `dependabot` scripts in `package.json` you can use for this

2022-10-31 16:25 UTC, cgsunkel approved these changes

2022-11-01 07:54 UTC, marijnkampf approved these changes

2022-11-01 09:39 UTC, merged