Update ActivityCardLabels.jsx
uktrade/data-hub-frontend pull request #5215
Opened 2023-01-18 11:35 UTC by bau123

Add labels to datahub events

## Description of change

Adds labels to datahub events

## Test instructions

Labels on datahub events

## Screenshots

### Before
<img width="1240" alt="Screenshot 2023-01-18 at 11 15 30" src="https://user-images.githubusercontent.com/15215184/213157622-cdb3a65e-decb-436e-b753-fe654360fa9f.png">

### After
<img width="1240" alt="Screenshot 2023-01-18 at 11 24 00" src="https://user-images.githubusercontent.com/15215184/213161348-19d36451-b78c-45eb-a79f-9cb5c55a35ec.png">

## Checklist

[//]: # 'When submitting a PR make sure the code review guidelines have been satisfied.
https://github.com/uktrade/data-hub-frontend/blob/main/docs/Code%20review%20guidelines.md'

- [ ] Has the branch been rebased to main?
- [ ] Automated tests (Any of the following when applicable: Unit, Functional or End-to-End)
- [ ] Manual compatibility testing (Browsers: Chrome, Firefox, Edge, Safari)

2023-01-18 11:56 UTC, onyela-o reviewed
Hello!
So I think we have shortened versions of the theme and service name for the labels instead of the full version e.g. A specific DIT export service or funding becomes something like 'Export service and funding' - I can't remember where the list is though :( 

EDIT: Found them I think src/client/components/ActivityFeed/constants.js and src/client/components/ActivityFeed/activities/InteractionUtils.js might be useful

2023-01-18 12:00 UTC, PaulWheatcroft approved these changes

2023-01-18 12:33 UTC, onyela-o requested changes

2023-01-18 12:33 UTC, onyela-o commented on src/client/components/ActivityFeed/activities/DataHubEvent.jsx
> +          kind={typeOfEvent}
If the `typeOfEvent` is null/empty - I think maybe the behaviour we would want would be for the kind label not to show at all, rather than say 'Not set'

2023-01-18 12:33 UTC, onyela-o commented on src/client/components/ActivityFeed/activities/DataHubEvent.jsx
> +  const serviceTypeSplit = serviceType.split(':')
This line might fail if the serviceType is set to 'Not set' as it will try and split it on a ':' and it doesn't exist in that case

2023-01-18 12:33 UTC, onyela-o commented on src/client/components/ActivityFeed/activities/DataHubEvent.jsx
> +  const theme = serviceTypeSplit[0]
Could do destructuring here instead so it's a bit neater like:
`const [ theme, service ] = serviceType.split(':')`
:)

2023-01-18 14:17 UTC, bau123 commented on src/client/components/ActivityFeed/activities/DataHubEvent.jsx
> +  const theme = serviceTypeSplit[0]
Added

2023-01-18 14:17 UTC, bau123 commented on src/client/components/ActivityFeed/activities/DataHubEvent.jsx
> +          kind={typeOfEvent}
Added

2023-01-18 14:41 UTC, bau123 commented on src/client/components/ActivityFeed/activities/DataHubEvent.jsx
> +  const serviceTypeSplit = serviceType.split(':')
All service should have a . so safe to split

2023-02-01 10:13 UTC, bau123 reviewed
Changes added

2023-02-01 10:54 UTC, onyela-o approved these changes
A few comments about naming but I'll approve so it doesn't block you again

2023-02-01 10:54 UTC, onyela-o commented on src/client/components/ActivityFeed/activities/DataHubEvent.jsx
> +  const [, service2] = serviceType.split(' : ')
Maybe rename this variable - I think we try and avoid naming something with a number

2023-02-01 10:54 UTC, onyela-o commented on src/client/components/ActivityFeed/activities/DataHubEvent.jsx
> +  const serviceOther = getServiceOtherText(service2)
Not sure about the serviceOther name - is it additional/extra text? Maybe serviceAdditionalText or something might be clearer

2023-02-01 10:54 UTC, onyela-o commented on src/client/components/ActivityFeed/constants.js
> +export const INTERACTION_SERVICEOTHER = {
INTERACTION_SERVICE_OTHER (or whatever the name will be) to keep the casing consistent :)

2023-02-01 11:22 UTC, merged