Update typeahead to allow users keep typing a filter keyword
uktrade/data-hub-frontend pull request #5923
Opened 2023-08-01 16:23 UTC by dredmonds

## Description of change

_Document what the PR does and why the change is needed_

## Test instructions

_What should I see?_

## Screenshots

### Before

_Add a screenshot_

### After

_Add a screenshot_

## Checklist

[//]: # 'When submitting a PR make sure the code review guidelines have been satisfied.
https://github.com/uktrade/data-hub-frontend/blob/main/docs/Code%20review%20guidelines.md'

- [ ] Has the branch been rebased to main?
- [ ] Automated tests (Any of the following when applicable: Unit, Functional or End-to-End)
- [ ] Manual compatibility testing (Browsers: Chrome, Firefox, Edge, Safari)

2023-08-02 10:24 UTC, backslashbaker approved these changes

2023-08-02 10:46 UTC, dredmonds commented on src/client/components/Typeahead/Typeahead.jsx
> +  const onInputKeyUp = (setTimeoutFn, averageTypingTimeout = 3000) => {
@chopkinsmade 
Well, redux implementation will firing the `TYPEAHEAD__OPTIONS_LOADED` https://github.com/uktrade/data-hub-frontend/blob/319ac8f4ece68731e3402b5f020a94f841839ea5/src/client/components/Typeahead/reducer.js#L48 after `throttle` dispatch. Which it highlighted the input in every `throttle` that causes input box to be clear-out.

The timeout above allows user to give a `throttle` filter results https://github.com/uktrade/data-hub-frontend/blob/319ac8f4ece68731e3402b5f020a94f841839ea5/src/client/components/Typeahead/tasks.js#L6 after `500` milisecond then when no  `onInput` events it won't reset the timer.

Therefore, the solution upon `onInputKeyUp` event start firing time-out then `onInput` event hits it will reset the time-out all over again.

2023-08-02 16:27 UTC, dredmonds commented on src/client/components/Typeahead/Typeahead.jsx
> +  const onInputKeyUp = (setTimeoutFn, averageTypingTimeout = 3000) => {
The `FORM__FIELD_SET_VALUE` action is in the highest level of implementation of `Typeahead` therefore not mean to touch on this occasion.

The objectives of this ticket is to keep the users typing on `typeahead` input box without pressing `backspace` to remove the previous input to key-in another filter string. Which shown video capture above. The acceptance criteria being discussed with the team are achieved.

2023-08-03 08:12 UTC, chopkinsmade requested changes
As shown in the image below, this change applies to all text entry even when no selection is made. 
![chrome_oCZkceHcMX](https://github.com/uktrade/data-hub-frontend/assets/102232401/581aaa6a-24b3-41b1-8aa0-b31e71e35bcc)

There is already an onClick event on the menu in the Typeahead.jsx file, you can probably add the highlighting logic to that so you meet the AC criteria

2023-08-03 09:01 UTC, dredmonds commented
> As shown in the image below, this change applies to all text entry even when no selection is made. ![chrome_oCZkceHcMX](https://user-images.githubusercontent.com/102232401/258046218-581aaa6a-24b3-41b1-8aa0-b31e71e35bcc.gif)
> 
> There is already an onClick event on the menu in the Typeahead.jsx file, you can probably add the highlighting logic to that so you meet the AC criteria

The specific requirements of this ticket is to keep users typing a filter keyword as opposed deleting previous input, neither filter results have a value or not. Therefore, highlighting the input keyword after `onClick` is another iteration of `Typeahead` new behaviours.

2023-08-03 10:24 UTC, cgsunkel commented
> As shown in the image below, this change applies to all text entry even when no selection is made. ![chrome_oCZkceHcMX](https://user-images.githubusercontent.com/102232401/258046218-581aaa6a-24b3-41b1-8aa0-b31e71e35bcc.gif)
> 
> There is already an onClick event on the menu in the Typeahead.jsx file, you can probably add the highlighting logic to that so you meet the AC criteria

I agree with @chopkinsmade on this. If someone has requested changes please do not re-request a review until you have addressed the issue.

2023-08-03 10:29 UTC, santoshdasa12345 approved these changes

2023-08-03 10:47 UTC, merged