Add Export Win - Support Provided (step 5 of 6)
uktrade/data-hub-frontend pull request #6462
Opened 2024-01-25 12:41 UTC by paulgain

## Description of change

This is step 5 of 6 of the Export Win user journey that enables Lead Officers to add an Export Win to Data Hub.

## Test instructions

Go to `/exportwins/create?step=support_provided&company=<company-uuid>`

## Screen
<img width="896" alt="Screenshot 2024-01-25 at 12 38 03" src="https://github.com/uktrade/data-hub-frontend/assets/964268/07f2e9ce-9502-4281-b27e-e5f9a0ecb82e">
shots
## Validation
<img width="946" alt="Screenshot 2024-01-25 at 12 39 52" src="https://github.com/uktrade/data-hub-frontend/assets/964268/63c37c22-f84a-4b75-90ae-ac2b9a943e7f">

## Checklist

[//]: # 'When submitting a PR make sure the code review guidelines have been satisfied.
https://github.com/uktrade/data-hub-frontend/blob/main/docs/Code%20review%20guidelines.md'

- [ ] Has the branch been rebased to main?
- [ ] Automated tests (Any of the following when applicable: Unit, Functional or End-to-End)
- [ ] Manual compatibility testing (Browsers: Chrome, Firefox, Edge, Safari)

2024-01-25 14:51 UTC, cgsunkel approved these changes

2024-01-26 12:00 UTC, peterhudec requested changes
Looks good, just a couple of things which can be simplified.

2024-01-26 12:13 UTC, DeanElliott96 requested changes
Looks good, maybe just a typo in the label which needs rephrased I think.

2024-01-26 12:13 UTC, DeanElliott96 commented on src/client/modules/ExportWins/Form/SupportProvidedStep.jsx
> +      label="What there as DBT campaign or event that contributed to this win?"
Think there is a typo here, might need to be rephrased?

2024-01-29 16:21 UTC, peterhudec approved these changes
Looks good now 💪

2024-01-29 16:39 UTC, DeanElliott96 approved these changes

2024-01-29 17:09 UTC, merged