Feature branch/tet 613 refactor investment project
uktrade/data-hub-frontend pull request #6465
Opened 2024-01-26 15:19 UTC by Richard-Pentecost

## Description of change

Refactor project investment pages so that the layout is rendered before the resource. Create new layouts for the investment pages to use so that inline resources can be rendered for better user experience if there are errors

## Test instructions

_What should I see?_

## Screenshots

### Before

_Add a screenshot_

### After

_Add a screenshot_

## Checklist

[//]: # 'When submitting a PR make sure the code review guidelines have been satisfied.
https://github.com/uktrade/data-hub-frontend/blob/main/docs/Code%20review%20guidelines.md'

- [x] Has the branch been rebased to main?
- [ ] Automated tests (Any of the following when applicable: Unit, Functional or End-to-End)
- [ ] Manual compatibility testing (Browsers: Chrome, Firefox, Edge, Safari)

2024-01-31 15:19 UTC, marijnkampf commented on src/client/components/InvestmentLocalHeader/index.jsx
> +                }}
Is this comment needed?

2024-01-31 15:19 UTC, marijnkampf commented on src/client/components/InvestmentLocalHeader/index.jsx
> +              </WatchTextContent> */}
See above

2024-01-31 15:19 UTC, marijnkampf commented on src/client/modules/Investments/Projects/Evidence/ProjectEvidence.jsx
> +          // >
Remove commented out code.

2024-01-31 16:04 UTC, swenban commented on src/client/components/InvestmentLocalHeader/index.jsx
> +                }}
WatchTextContent was relocated to the investment layout so I've now removed this commented out code

2024-01-31 16:07 UTC, swenban commented on src/client/components/InvestmentLocalHeader/index.jsx
> +              </WatchTextContent> */}
This has now been removed

2024-01-31 16:12 UTC, swenban commented on src/client/modules/Investments/Projects/Evidence/ProjectEvidence.jsx
> +          // >
Thank you, this has now been removed

2024-01-31 16:15 UTC, marijnkampf approved these changes

2024-02-01 12:59 UTC, oliverjwroberts requested changes
The changes you have made all look good to me and are working as expected on my end. In fact, I really like how the pages now load. 

However, I did note that when testing if the error messages load with an unknown project ID, clicking on the Admin tab caused an error and the app to crash.

After clicking on the `Evidence` tab, the error messages appear as expected:

![image](https://github.com/uktrade/data-hub-frontend/assets/47334342/b0373354-e276-4522-88a2-13c0823f4f82)

After clicking on the `Admin` tab, the app crashed:

![image](https://github.com/uktrade/data-hub-frontend/assets/47334342/74d0837a-2dad-4c7d-b734-33808103ecc8)

Console output:
```
error: uncaughtException: Cannot destructure property 'id' of 'res.locals.investment' as it is undefined.
TypeError: Cannot destructure property 'id' of 'res.locals.investment' as it is undefined.
[nodemon] app crashed - waiting for file changes before starting...
```

This can also be replicated on the staging environment with a 504 error, so most likely a pre-existing issue.

I'd be happy to discuss further, but thought we might want to investigate some more before publishing this change as it could potentially increase the chance of users accidentally experiencing the issue.

2024-02-08 15:17 UTC, oliverjwroberts approved these changes

2024-02-08 16:02 UTC, merged