Reactify OMIS quote page
uktrade/data-hub-frontend pull request #6515
Opened 2024-02-12 12:26 UTC by cgsunkel

## Description of change

The OMIS quote page has been reactified. The additions diff is so large because a new dependency was added.

## Test instructions

Go to the quote page for a draft order. You should be able to submit the quote.
Go to the quote page for an order where the quote is awaiting acceptance. You should be able to withdraw the quote.
Go to the quote page for any other non-cancelled order. The quote and T&C's should render as usual.

## Screenshots

This is an old quote which is why DIT is mentioned in the content.

![Screenshot 2024-02-12 at 12-23-50 Quote - RVK689_22 - Orders (OMIS) - DBT Data Hub](https://github.com/uktrade/data-hub-frontend/assets/36161814/e854d4fd-2148-4cde-95b4-b140efd7d5a1)

## Checklist

[//]: # 'When submitting a PR make sure the code review guidelines have been satisfied.
https://github.com/uktrade/data-hub-frontend/blob/main/docs/Code%20review%20guidelines.md'

- [ ] Has the branch been rebased to main?
- [ ] Automated tests (Any of the following when applicable: Unit, Functional or End-to-End)
- [ ] Manual compatibility testing (Browsers: Chrome, Firefox, Edge, Safari)

2024-02-12 12:27 UTC, cgsunkel commented on package.json
> +    "remark-gfm": "^4.0.0",
This was added in order to allow `react-markdown` to render links properly

2024-02-12 12:29 UTC, cgsunkel commented on src/client/modules/Omis/OMISTermsAndConditions.jsx
The API markdown for this was written with Nunjucks in mind, meaning that our React markdown component can't parse it properly. In order to prevent any breakages within the OMIS frontend I have replicated the T&Cs in this repo.

The API markdown also contains several accessibility violations, which have been rectified here.

2024-02-12 12:30 UTC, cgsunkel commented on src/client/modules/Omis/OMISLocalHeader.jsx
When you try to view the quote for a cancelled order it renders an empty page. This isn't desirable so the link has been removed.

2024-02-12 12:32 UTC, cgsunkel commented on src/client/modules/Omis/OrderQuote.jsx
> +    </H1>
The react markdown component we use would not recognise the existing heading as a heading, as this is always the same this has been rendered separately.

2024-02-16 09:24 UTC, oliverjwroberts requested changes
Hi @cgsunkel, it looks good to me, apart from a couple of minor things:

1. In your screenshot, the quote preview has the text `The DIT Contact shall be X. If you do not have contact details for the DIT Contact, please contact omis.orders@digital.trade.gov.uk`. However, on my local instance, when I previewed an order, it was missing the contact email address from the end of the sentence: `The DBT Contact shall be X. If you do not have contact details for the DBT Contact, please contact .`; Is that possibly just something I'm missing locally?

2. The acceptance options don't appear to be bulleted points, like they were previously on the quote preview (as can be seen in dev). Can these be added back in, please?

```
Please confirm your acceptance of this Quote by:

- indicating that you have read and accepted the terms and conditions annexed to this Quote and the Charges by ticking the box ‘I accept the Charges and the Terms and Conditions’; and
- selecting ‘Accept quote’.
```

Let me know what you think, and as always, I'd be happy to discuss further if needed.

2024-02-16 10:33 UTC, cgsunkel commented
>     1. In your screenshot, the quote preview has the text `The DIT Contact shall be X. If you do not have contact details for the DIT Contact, please contact omis.orders@digital.trade.gov.uk`. However, on my local instance, when I previewed an order, it was missing the contact email address from the end of the sentence: `The DBT Contact shall be X. If you do not have contact details for the DBT Contact, please contact .`; Is that possibly just something I'm missing locally?

This is just because the quote I used for the screenshot was an older one from before the DIT/DBT content change (this is because most of the quotes in dev are on the older side). If you find an older quote locally you should see the same DIT text.

>     2. The acceptance options don't appear to be bulleted points, like they were previously on the quote preview (as can be seen in dev). Can these be added back in, please?

This is part of the problematic markdown embedded into the quote. For some reason our dependency for handling markdown cannot recognise these as bullet points. These have been left as-is for a couple of reasons:
- The 'correspondence will be between our representatives' section is also formatted like this (and was like this previously).
- I wasn't comfortable to make further amendments to the quote markdown as this would have added further complexity to the PR.
- The markdown in the API cannot be changed without causing potential issues in the OMIS frontend

2024-02-16 13:07 UTC, oliverjwroberts approved these changes
@cgsunkel, I managed to find an older quote and as you said it would be, the email address was present. I also note the same issue with the `correspondence will be between our representatives` section.

Those reasons sound good enough for me, so I'm happy to approve as is. Is it worth adding a ticket to the backlog, or writing up something, just so we've captured it?

2024-02-16 14:03 UTC, cgsunkel commented
> Those reasons sound good enough for me, so I'm happy to approve as is. Is it worth adding a ticket to the backlog, or writing up something, just so we've captured it?

At some point in the future we'll be migrating the OMIS FE into Data Hub (in the same manner as with Export Wins) so I would assume this would be captured as part of that work

2024-02-19 13:48 UTC, paulgain commented on src/client/modules/Omis/OrderQuote.jsx
> +            {order.status === 'draft' && (
For improved readability it would be good to see all the statuses together and defined as constants. There are a couple of instances of `order.status === 'draft'` and `order.status === 'quote_awaiting_acceptance'` that need refactoring, the same applies to `cancelled`.

2024-02-19 13:49 UTC, paulgain approved these changes
LGTM, just a single comment.

2024-02-19 15:50 UTC, merged