Dependabot 2024 02 27
uktrade/data-hub-frontend pull request #6560
Opened 2024-02-27 12:13 UTC by swenban

## Description of change

This week's Dependabot updates.

## Checklist

[//]: # 'When submitting a PR make sure the code review guidelines have been satisfied.
https://github.com/uktrade/data-hub-frontend/blob/main/docs/Code%20review%20guidelines.md'

- [ ] Has the branch been rebased to main?
- [ ] Automated tests (Any of the following when applicable: Unit, Functional or End-to-End)
- [ ] Manual compatibility testing (Browsers: Chrome, Firefox, Edge, Safari)

2024-02-27 13:58 UTC, oliverjwroberts requested changes
Just one thing from me, otherwise looks good 😄

2024-02-27 13:58 UTC, oliverjwroberts commented on test/sandbox/package.json
> +    "nodemon": "^3.1.0"
Should `nodemon` be upgraded in the root `package.json` too?

2024-02-27 15:39 UTC, swenban commented on test/sandbox/package.json
> +    "nodemon": "^3.1.0"
The sandbox PRs are raised separately from the main frontend ones so it's not currently needed

2024-02-27 16:23 UTC, cgsunkel approved these changes

2024-02-28 07:42 UTC, oliverjwroberts approved these changes

2024-02-28 10:05 UTC, merged