CLS2-997 Reorder EYB leads filters
uktrade/data-hub-frontend pull request #7218
Opened 2024-10-07 15:50 UTC by swenban

## Description of change

Change the order of the filters on the EYB Leads collection page

**From:**
-Company name
-Sector of interest
-Value

**To:**
-Value
-Sector of interest
-Company name

## Test instructions

_What should I see?_

## Screenshots

### Before

_Add a screenshot_

### After

_Add a screenshot_

## Checklist

[//]: # 'When submitting a PR make sure the code review guidelines have been satisfied.
https://github.com/uktrade/data-hub-frontend/blob/main/docs/Code%20review%20guidelines.md'

- [ ] Has the branch been rebased to main?
- [ ] Automated tests (Any of the following when applicable: Unit, Functional or End-to-End)
- [ ] Manual compatibility testing (Browsers: Chrome, Firefox, Edge, Safari)

2024-10-07 15:54 UTC, samuele-mattiuzzo approved these changes

2024-10-07 15:55 UTC, oliverjwroberts approved these changes

2024-10-08 08:42 UTC, samuele-mattiuzzo commented on Makefile
> +wait-for-frontend = dockerize -wait tcp://localhost:3000/pingdom -timeout 5m -wait-retry-interval 5s
ah this was already in main (merged my pr for CLS2-906 yesterday)

2024-10-08 08:45 UTC, samuele-mattiuzzo requested changes
I would remove the spacing added since it just applies to this page and causes inconsistency with the rest of the FE

2024-10-08 08:45 UTC, samuele-mattiuzzo commented on src/client/modules/Investments/EYBLeads/EYBLeadsCollection.jsx
> +          &nbsp;
being that this is most likely going to happen elsewhere in DH, would it not be worth having it as part of the styling for `CollectionFilters` so that there's always a margin-top that's consistent?

2024-10-08 09:41 UTC, swenban commented on src/client/modules/Investments/EYBLeads/EYBLeadsCollection.jsx
> +          &nbsp;
Our designer has agreed we should just apply it to the EYB leads page for now. Further work to the filters is planned for future iterations so we will explore the use of groups and padding then

2024-10-08 09:43 UTC, swenban commented on Makefile
> +wait-for-frontend = dockerize -wait tcp://localhost:3000/pingdom -timeout 5m -wait-retry-interval 5s
I've now done a rebase

2024-10-08 09:46 UTC, samuele-mattiuzzo approved these changes

2024-10-08 09:53 UTC, oliverjwroberts approved these changes

2024-10-08 10:10 UTC, merged