CLS2-994 Field names updates
uktrade/data-hub-frontend pull request #7238
Opened 2024-10-16 11:02 UTC by samuele-mattiuzzo

## Description of change

EYB lead fields that need updating (because names have changed)

Relevant API branches: feature: [feature/CLS2-899-ingest-eyb-lead-data](https://github.com/uktrade/data-hub-api/tree/feature/CLS2-899-ingest-eyb-lead-data); PR [feature/refactor-eyb-lead-schema](https://github.com/uktrade/data-hub-api/tree/feature/refactor-eyb-lead-schema)

## Checklist

[//]: # 'When submitting a PR make sure the code review guidelines have been satisfied.
https://github.com/uktrade/data-hub-frontend/blob/main/docs/Code%20review%20guidelines.md'

- [ ] Has the branch been rebased to main?
- [ ] Automated tests (Any of the following when applicable: Unit, Functional or End-to-End)
- [ ] Manual compatibility testing (Browsers: Chrome, Firefox, Edge, Safari)

2024-10-17 11:08 UTC, oliverjwroberts requested changes

2024-10-17 11:08 UTC, oliverjwroberts commented on src/client/modules/Investments/EYBLeads/transformers.js
> +  address_country,
In the triage data`location` is now `proposed_investment_region`

2024-10-17 11:08 UTC, oliverjwroberts commented on src/client/modules/Investments/EYBLeads/transformers.js
> +    { label: 'Location', value: address_country ? address_country.name : '' },
Same as above.

2024-10-17 11:08 UTC, oliverjwroberts commented on test/functional/cypress/fakers/eyb-leads.js
>    location: WALES,
`location` will need changing to `proposed_investment_region` here as well

2024-10-17 11:08 UTC, oliverjwroberts commented on test/functional/cypress/specs/investments/eyb-leads-spec.js
> +        .should('contain', `Location ${eybLead.address.country.name}`)
Same again, `location` is `proposed_investment_region`, rather than address country

2024-10-17 11:08 UTC, oliverjwroberts commented on test/sandbox/fixtures/v4/investment/eyb-lead-list.json
> +      "proposed_investment_city": "Cardiff",
Line above will need to be `proposed_investment_region`, rather than `location`.

2024-10-17 11:08 UTC, oliverjwroberts commented on test/sandbox/fixtures/v4/investment/eyb-lead-list.json
>        },
Same again for line 106

2024-10-17 11:08 UTC, oliverjwroberts commented on test/sandbox/fixtures/v4/investment/eyb-lead-list.json
>        },
Same again for line 177.

2024-10-17 12:11 UTC, swenban approved these changes

2024-10-17 12:35 UTC, oliverjwroberts approved these changes
Thanks for making those changes Marijn. Just to flag, if there were leads in the respective environments, there may be conflicts/errors as these fields do not yet exist in EYBLead table. However, because there are no leads, we should be good. Once API branch `feature/CLS2-899-ingest-eyb-lead-data` is merged in, this will be resolved.

2024-10-24 12:04 UTC, p3dr0migue1 approved these changes

2024-10-24 12:09 UTC, merged